/**
 * The tool loop: a direct engine's turn, round by round (PLAN.md §5.1). Every round the tool
 * registry is rebuilt and the prompt materialised from the log, the completion is recorded
 * before anything acts on it, and each tool call is logged on both sides.
 */
import { createToolRegistry, type ToolRegistry } from "../tools/index.ts";
import { materializePrompt, type StandingContext } from "./prompt.ts";
import { compactThread, DEFAULT_THRESHOLD_PERCENT } from "./compact.ts";
import { EngineId } from "./model-roles.ts";
import { EngineFailure, StopReason } from "./outage.ts";
import { HostMethod } from "./host-methods.ts";
import { EventKind, RunEvent } from "./run-events.ts";
import { TurnStop, sayInTurn } from "./turn-record.ts";
import { lookAtPictures, turnBriefing } from "./turn-prompts.ts";
import { OUTPUT_LIMIT_NOTE } from "./tool-loop-prompts.ts";
import { picturesNotShown } from "./unseen-pictures-prompts.ts";
import type { TurnOptions, TurnOutcome } from "./turn-loop.ts";
import type { HarnessCtx } from "../types/harness.d.ts";
import type {
  CompleteResponse,
  ContextPolicy,
  EngineDescriptor,
  Message,
  MessageImage,
  ToolCall,
} from "../types/host-api.d.ts";

/** How many tool rounds a turn gets unless it names its own ceiling. */
const DEFAULT_MAX_ROUNDS = 24;
/** The most pictures a turn shows the model at once: the latest ones. */
const MAX_TURN_IMAGES = 4;
/** A rough count of characters per token, for the tool definitions the engine has not counted. */
const CHARS_PER_TOKEN = 4;
/** Room kept free for the reply. */
const REPLY_RESERVE_TOKENS = 4096;
/** What one attached picture costs the prompt. */
const IMAGE_TOKENS = 2048;

/** Whose compaction threshold a context policy carries (`mode`): the studio's default, or the user's. */
const ContextPolicyMode = {
  Default: "default",
  Custom: "custom",
} as const satisfies Record<string, ContextPolicy["mode"]>;

/** What the chat is told. */
const MESSAGE = {
  cancelled: "cancelled",
  maxRounds: (rounds: number) => `turn stopped after ${rounds} tool rounds`,
  deadline: "the run's wall clock ran out mid-turn — stopping with the progress so far",
  contextTooLarge: (percent: number, reason: string | undefined) =>
    `Context cannot fit the chosen ${percent}% threshold: ${reason ?? "recent work and fixed instructions remain too large"}. Increase the threshold or shorten the request. Existing work is preserved.`,
  outOfUsage: (engine: string, detail: string | undefined) =>
    `${engine} is out of usage: ${detail ?? "usage limit reached"}. Nothing was generated by another model — wait for the reset, sign into a different account (Review → Models → "Use a different account…"), or pick another engine and resend.`,
  continuingOn: (engine: string, kind: string, detail: string | undefined, next: string) =>
    `${engine} is ${kind === EngineFailure.RateLimit ? "throttled" : "unreachable"} (${detail ?? kind}) — continuing the run on ${next} so the build isn't lost. Each reply is labeled with the model that wrote it.`,
  notSwitched: (engine: string, kind: string, detail: string | undefined) =>
    `${engine} is ${kind === EngineFailure.RateLimit ? "throttled right now" : "unreachable"} (${detail ?? kind}). I didn't switch you to another model — wait a bit and resend, or pick a different engine.`,
} as const;

/** The engine is throttled or unreachable: a wait (or another engine) can get past it. */
export function isThrottle(kind: string): boolean {
  return kind === EngineFailure.RateLimit || kind === EngineFailure.Unavailable;
}

/** A throttle the host named a fallback engine for. */
export function canFallBack(kind: string, fallbacks: readonly string[]): boolean {
  return isThrottle(kind) && fallbacks.length > 0;
}

/** What the picked model can actually hold — the number every context decision hangs off. */
export function resolveContextWindow(
  described: readonly EngineDescriptor[],
  engine: string,
  model: string | null | undefined,
): number | null {
  const descriptor = described.find((e) => e.id === engine);
  if (!descriptor) return null;
  const id = model ?? descriptor.defaultModel;
  return descriptor.models?.find((m) => m.id === id)?.contextWindow ?? null;
}

type Prompt = Awaited<ReturnType<typeof materializePrompt>>;

/** What the loop carries from round to round: a fallback changes the engine under it. */
interface LoopState {
  engine: string;
  model: string | undefined;
  contextWindow: number | null;
  /** Pixels stay out of the event log (same rule as the judge). Kept for this turn only. */
  images: MessageImage[];
  /** Whether the model takes images; asked once a picture is to be sent, again after a fallback. */
  seesImages?: boolean;
  /** What the system prompt stands on, as the turn's first prompt read it (prompt.ts). */
  standing?: StandingContext;
}

/** A completion: the engine's answer, the outcome that ends the turn, or neither (try again). */
interface Completion {
  response?: CompleteResponse;
  outcome?: TurnOutcome;
}

/** Run a direct engine's turn: rounds of prompt, completion and tool calls until it answers. */
export async function runToolLoop(ctx: HarnessCtx, options: TurnOptions): Promise<TurnOutcome> {
  const maxRounds = options.maxRounds ?? DEFAULT_MAX_ROUNDS;
  const state: LoopState = {
    engine: options.engine ?? EngineId.Ollama,
    model: options.model,
    contextWindow: options.contextWindow ?? null,
    // Stills the user named by path are attached up front so the model looks at them instead of hunting.
    images: (options.stills ?? []).map((still) => ({ label: still.label, mimeType: still.mimeType, data: still.data })),
  };
  for (let round = 0; ; round++) {
    const stop = await stopBeforeRound(ctx, options, round, maxRounds);
    if (stop) return stop;
    // ① rebuilt every round — self-installed tools appear here
    const tools = await createToolRegistry(ctx, options);
    // ② full replay → prompt
    const prompt = await promptThatFits(ctx, options, state, tools);
    if (!prompt) return { stopped: TurnStop.Cancelled, round };
    const { response, outcome } = await complete(ctx, options, state, tools, prompt, round);
    if (outcome) return outcome;
    if (!response) continue;
    const answered = await actOn(ctx, options, state, tools, response, round);
    if (answered) return answered;
  }
}

async function recordError(ctx: HarnessCtx, turnId: string, message: string): Promise<void> {
  await ctx.call(HostMethod.TurnAppend, { turnId, batch: [{ type: EventKind.Error, message }] });
}

/** The reasons a turn ends before its next round: out of rounds, stopped, or out of time. */
async function stopBeforeRound(
  ctx: HarnessCtx,
  options: TurnOptions,
  round: number,
  maxRounds: number,
): Promise<TurnOutcome | null> {
  const { turnId } = options;
  if (round >= maxRounds) {
    await recordError(ctx, turnId, MESSAGE.maxRounds(maxRounds));
    return { stopped: TurnStop.MaxRounds, round };
  }
  if (ctx.cancelled) {
    await recordError(ctx, turnId, MESSAGE.cancelled);
    return { stopped: TurnStop.Cancelled, round };
  }
  // A run's clock reaches inside the turn: a local build owes the deadline the same respect
  // a delegated one already pays via timeoutMs. Everything done so far is durable — in the
  // log and on disk — so stopping between rounds loses nothing.
  if (options.deadlineMs && Date.now() > options.deadlineMs) {
    await recordError(ctx, turnId, MESSAGE.deadline);
    return { stopped: TurnStop.Deadline, round };
  }
  return null;
}

/**
 * This round's prompt, compacted first when it would not fit the context threshold. Null when
 * the user stopped the turn during the compaction; throws when even the compacted one is too big.
 */
async function promptThatFits(
  ctx: HarnessCtx,
  options: TurnOptions,
  state: LoopState,
  tools: ToolRegistry,
): Promise<Prompt | null> {
  const { threadId } = options;
  const { engine, model, contextWindow } = state;
  const extraSystem = turnBriefing(options);
  const policy = await ctx.call(HostMethod.ContextPolicy, { engine, model, threadId });
  const percent = (
    policy?.policy?.mode === ContextPolicyMode.Custom ? policy.policy.thresholdPercent : DEFAULT_THRESHOLD_PERCENT
  ) as number;
  const materialize = async (preserveHistory: boolean) => {
    const built = await materializePrompt(ctx, {
      threadId,
      tools,
      standing: state.standing,
      ...(options as Omit<TurnOptions, "threadId">),
      extraSystem,
      contextWindow,
      preserveHistory,
    });
    // Every later round of this turn stands on what the first one read, so its prefix holds.
    state.standing ??= built.standing;
    return built;
  };
  const prompt = await materialize(!!contextWindow);
  const toolsTokens = Math.ceil(JSON.stringify(tools.definitions()).length / CHARS_PER_TOKEN);
  // Only the latest pictures ride the prompt (`withTurnImages`): room for those, not for every one taken.
  const imageTokens = Math.min(state.images.length, MAX_TURN_IMAGES) * IMAGE_TOKENS;
  const fixedTokens = prompt.tokens.system + toolsTokens + REPLY_RESERVE_TOKENS + imageTokens;
  if (!contextWindow) return prompt;
  const budget = Math.floor((contextWindow * percent) / 100);
  if (prompt.tokens.full + fixedTokens <= budget) return prompt;

  ctx.setStatus?.("compacting the conversation");
  const outcome = await compactThread(ctx, {
    threadId,
    engine,
    model,
    contextWindow,
    thresholdPercent: percent,
    fixedTokens,
    force: true,
    automatic: true,
  });
  if (ctx.cancelled) return null;
  const compacted = await materialize(true);
  if (compacted.tokens.full + fixedTokens > budget) throw new Error(MESSAGE.contextTooLarge(percent, outcome.reason));
  return compacted;
}

/** Ask the engine for this round's answer; a failure ends the turn, switches engine, or throws. */
async function complete(
  ctx: HarnessCtx,
  options: TurnOptions,
  state: LoopState,
  tools: ToolRegistry,
  prompt: Prompt,
  round: number,
): Promise<Completion> {
  try {
    const response = await ctx.call(HostMethod.EngineComplete, {
      engine: state.engine,
      model: state.model,
      threadId: options.threadId,
      systemPrompt: prompt.systemPrompt,
      messages: await withPictures(ctx, state, prompt.messages),
      tools: tools.definitions(),
      toolRegistryRevision: tools.toolRegistryRevision,
      ...(options.deadlineMs ? { timeoutMs: Math.max(1, options.deadlineMs - Date.now()) } : {}),
      ...(options.effort ? { effort: options.effort } : {}),
      ...(options.preferences ? { preferences: options.preferences } : {}),
    });
    return { response };
  } catch (err: any) {
    return completionFailed(ctx, options, state, err, round);
  }
}

async function completionFailed(
  ctx: HarnessCtx,
  options: TurnOptions,
  state: LoopState,
  err: any,
  round: number,
): Promise<Completion> {
  const { turnId } = options;
  const { engine } = state;
  const fallbacks: string[] = err?.fallbacks ?? [];
  const kind: string = err?.kind ?? EngineFailure.Other;
  const fallbackReady = canFallBack(kind, fallbacks);
  // A run's build turn (runId set) answers to the gauntlet, which has its own richer
  // policies — strike counting, throttle waits, usage_limit stops that preserve the
  // worktree. Swallowing the error here would blind all of them: rethrow instead.
  const inRun = Boolean(options.runId);
  if (inRun && !fallbackReady) throw err;
  // A weekly/monthly cap outlives any wait, and a run on the wrong model is not the
  // run the user paid for — stop honestly instead of substituting.
  if (kind === EngineFailure.UsageLimit) {
    await sayInTurn(ctx, turnId, MESSAGE.outOfUsage(engine, err?.message));
    return { outcome: { stopped: TurnStop.EngineLimited, round, engine } };
  }
  // Subscription throttles must not end the run (PLAN.md §6.3 / M2 acceptance) — but a
  // swap the user never hears about reads as deception. Fall back only mid-run or
  // mid-commission, and say so in the chat, not just in a log event.
  const commissioned = inRun || Boolean(options.loop || options.autopilot);
  if (fallbackReady && commissioned) {
    await switchEngine(ctx, turnId, state, fallbacks[0], kind, err?.message);
    return {};
  }
  if (isThrottle(kind)) {
    await sayInTurn(ctx, turnId, MESSAGE.notSwitched(engine, kind, err?.message));
    return { outcome: { stopped: TurnStop.EngineLimited, round, engine } };
  }
  // Stop reaches into the generation now (engine.abort) — an aborted completion is the
  // user's stop landing, not a failure, whichever side of the race reported first.
  if (kind === EngineFailure.Aborted || ctx.cancelled) {
    await recordError(ctx, turnId, MESSAGE.cancelled);
    return { outcome: { stopped: TurnStop.Cancelled, round } };
  }
  throw err;
}

/** Continue the turn on the fallback engine — out loud, in the log and in the chat. */
async function switchEngine(
  ctx: HarnessCtx,
  turnId: string,
  state: LoopState,
  next: string,
  kind: string,
  detail: string | undefined,
): Promise<void> {
  const from = state.engine;
  await ctx.call(HostMethod.TurnAppend, {
    turnId,
    batch: [
      {
        type: EventKind.Custom,
        event_type: RunEvent.EngineFallback,
        payload: { from, to: next, kind, message: detail ?? "" },
      },
    ],
  });
  await sayInTurn(ctx, turnId, MESSAGE.continuingOn(from, kind, detail, next));
  ctx.notify("engine.fallback", { from, to: next, kind });
  state.engine = next;
  state.model = undefined;
  state.seesImages = undefined;
  state.contextWindow = resolveContextWindow(await ctx.call(HostMethod.EngineDescribe), next, undefined);
}

/**
 * Record the engine's answer, then act on it: a plain reply ends the turn, tool calls run in
 * order. Null when the turn goes on to another round.
 */
async function actOn(
  ctx: HarnessCtx,
  options: TurnOptions,
  state: LoopState,
  tools: ToolRegistry,
  response: CompleteResponse,
  round: number,
): Promise<TurnOutcome | null> {
  if (response.stopReason === StopReason.Length) return cutOff(ctx, options, state, response);
  // ③ durable before acting
  await ctx.call(HostMethod.TurnAppend, {
    turnId: options.turnId,
    batch: [{ type: EventKind.Messages, messages: [response.message], usage: response.usage }],
  });
  await recordContextUsage(ctx, options, state, response);
  const calls = response.message.tool_calls ?? [];
  if (calls.length === 0) {
    ctx.notify("chat.message", { role: "assistant", content: response.message.content });
    return { stopped: TurnStop.Done, round, engine: state.engine };
  }
  return runToolCalls(ctx, options.turnId, tools, calls, state, round);
}

/**
 * A reply its output limit cut off. Its tool calls are not an executable request — even a call
 * that parsed may be one of a batch the model never finished — so none runs and none is replayed
 * as made: the text is kept, the model is told why, and the next round asks again (bounded by
 * the turn's rounds).
 */
async function cutOff(
  ctx: HarnessCtx,
  options: TurnOptions,
  state: LoopState,
  response: CompleteResponse,
): Promise<null> {
  const { tool_calls: _dropped, ...message } = response.message;
  await ctx.call(HostMethod.TurnAppend, {
    turnId: options.turnId,
    batch: [
      { type: EventKind.Messages, messages: [message], usage: response.usage },
      { type: EventKind.Messages, messages: [{ role: "system", content: OUTPUT_LIMIT_NOTE }] },
    ],
  });
  await recordContextUsage(ctx, options, state, response);
  return null;
}

/**
 * The engine reports the EXACT prompt size it just processed — no estimating. Logged so the
 * context meter survives restarts, notified so the UI updates live.
 */
async function recordContextUsage(
  ctx: HarnessCtx,
  options: TurnOptions,
  state: LoopState,
  response: CompleteResponse,
): Promise<void> {
  const promptTokens = response.usage?.input_tokens ?? 0;
  if (promptTokens <= 0) return;
  const { engine, model, contextWindow } = state;
  const percent = contextWindow ? Math.round((promptTokens / contextWindow) * 100) : null;
  await ctx.call(HostMethod.TurnAppend, {
    turnId: options.turnId,
    batch: [
      {
        type: EventKind.Custom,
        event_type: RunEvent.ContextUsage,
        payload: {
          engine,
          requestedModel: model ?? null,
          model: response.model ?? null,
          source: "provider",
          promptTokens,
          contextWindow,
          percent,
        },
      },
    ],
  });
  ctx.notify("context.usage", {
    threadId: options.threadId,
    engine,
    model: response.model ?? model ?? null,
    promptTokens,
    contextWindow,
    percent,
  });
}

/** Run this round's tool calls in order; a tool may end the turn. Null when the turn goes on. */
async function runToolCalls(
  ctx: HarnessCtx,
  turnId: string,
  tools: ToolRegistry,
  calls: readonly ToolCall[],
  state: LoopState,
  round: number,
): Promise<TurnOutcome | null> {
  for (const call of calls) {
    if (ctx.cancelled) return null;
    await ctx.call(HostMethod.TurnAppend, {
      turnId,
      batch: [
        { type: "tool_requested", tool_call_id: call.id, request: { name: call.name, arguments: call.arguments } },
      ],
    });
    ctx.notify("tool.started", { name: call.name, id: call.id });

    const result = await tools.execute(call, ctx);
    collectImages(result, state.images);
    await ctx.call(HostMethod.TurnAppend, {
      turnId,
      batch: [
        {
          type: "tool_result",
          tool_call_id: call.id,
          result: { ok: result.ok, content: result.content, ...(result.details ? { details: result.details } : {}) },
        },
      ],
    });
    ctx.notify("tool.finished", { name: call.name, id: call.id, ok: result.ok });

    // A tool may ask the turn to stop — `restart_studio` does, because the process is about
    // to be replaced and anything after this point would be written by a dead self.
    if (result.stopTurn) return { stopped: result.stopTurn, round, engine: state.engine, details: result.details };
  }
  return null;
}

/**
 * The round's messages with this turn's pictures. A local model that cannot see images refuses a
 * request that carries them, so it hears that they exist instead of receiving the pixels.
 */
async function withPictures(ctx: HarnessCtx, state: LoopState, messages: Message[]): Promise<Message[]> {
  if (!state.images.length) return messages;
  state.seesImages ??= await seesImages(ctx, state);
  if (state.seesImages) return withTurnImages(messages, state.images);
  return [...messages, { role: "user", content: picturesNotShown(imageLabels(state.images.slice(-MAX_TURN_IMAGES))) }];
}

/** Whether the turn's model takes images; a model the engine does not describe is taken to. */
async function seesImages(ctx: HarnessCtx, state: LoopState): Promise<boolean> {
  const described: readonly EngineDescriptor[] = await ctx.call(HostMethod.EngineDescribe).catch(() => []);
  const descriptor = described.find((e) => e.id === state.engine);
  const id = state.model ?? descriptor?.defaultModel;
  return descriptor?.models?.find((m) => m.id === id)?.supportsVision !== false;
}

/** The pictures' names as the model reads them. */
function imageLabels(images: MessageImage[]): string {
  return images.map((img, index) => img.label || `shot ${index + 1}`).join(", ");
}

function withTurnImages(messages: Message[], images: MessageImage[]): Message[] {
  if (!images.length) return messages;
  const kept = images.slice(-MAX_TURN_IMAGES);
  const labels = imageLabels(kept);
  return [
    ...messages,
    {
      role: "user",
      content: lookAtPictures(labels),
      images: kept.map((img) => ({
        mimeType: img.mimeType || "image/jpeg",
        data: img.data,
        ...(img.label ? { label: img.label } : {}),
      })),
    },
  ];
}

function collectImages(result: { images?: MessageImage[] } | null | undefined, sink: MessageImage[]): void {
  for (const image of result?.images ?? []) {
    if (image?.data) sink.push(image);
  }
}
