// GENERATED by scripts/gen-harness-types.ts from src/shared/harness-api.ts and src/shared/protocol.ts
// — do not edit. The host contract as the harness sees it: `ctx.call(method, params)` sends
// `HarnessHostApi[method]["params"]` and resolves to `HarnessHostApi[method]["result"]`, and
// `dispatch(action)` receives a `DispatchAction`.
// An app update replaces this file; your own types belong in your own modules.

export type WorkClass = 'user' | 'improvement';
// ↑ src/shared/harness-api.ts

/** Budget class of a completion or delegation; anything but `improvement` is user work. */
export type HarnessWorkClass = WorkClass;
// ↑ src/shared/harness-api.ts

/** A snapshot's reach: the harness workspace, the game, or both. */
export type HarnessSnapshotScope = "harness" | "game" | "both";
// ↑ src/shared/harness-api.ts

/**
 * Where a self-edit tried in a validation fork stopped: the change itself was refused (a path that
 * is not the harness's own), it added type errors, the type check ran out of time, the copy did
 * not boot, or the check could not run at all (no compiler in this build) — which refuses too.
 */
export type SelfEditStage = "refused" | "types" | "timeout" | "boot" | "unavailable";
// ↑ src/shared/harness-api.ts

/** `guardian.validate_edit`'s answer: what passed, or where it stopped and why, as bounded text. */
export type SelfEditVerdict = { ok: true; checked: string[] } | { ok: false; stage: SelfEditStage; message: string };
// ↑ src/shared/harness-api.ts

/** What `guardian.write_self` did: the change written between two host snapshots, or why not. */
export type SelfWriteResult =
  | { ok: true; file: string; snapshotId: string; postSnapshotId: string; checked: string[] }
  | { ok: false; stage: SelfEditStage; message: string };
// ↑ src/shared/harness-api.ts

/** An image the harness reads from a game folder: the bytes decide the type, never the extension. */
export interface GameImageRead {
  kind: "image";
  mimeType: string;
  data: string;
  bytes: number;
  file: string;
}
// ↑ src/shared/harness-api.ts

/** A stills source for `preview.pair`: inline bytes, or a path under the studio's runs. */
export interface StillSource {
  base64?: string;
  path?: string;
}
// ↑ src/shared/harness-api.ts

/**
 * `run.exec`'s answer as it crosses the pipe (`substrate/spawn.ts` `RunResult`): the signal is
 * whatever name the process died of.
 */
export interface ExecResult {
  code: number | null;
  signal: string | null;
  stdout: string;
  stderr: string;
  durationMs: number;
  timedOut: boolean;
  truncated: boolean;
  sandboxed: boolean;
  command: string;
  cwd: string;
}
// ↑ src/shared/harness-api.ts

export type Role = "system" | "user" | "assistant" | "tool";
// ↑ src/shared/event-log.ts

/** A still the model should look at — JPEG/PNG/WebP bytes, never a file path. */
export interface MessageImage {
  mimeType: string;
  /** Raw bytes as base64. */
  data: string;
  /** Short caption for the accompanying text ("BUILD A / close"). */
  label?: string;
}
// ↑ src/shared/event-log.ts

export interface ToolCall {
  id: string;
  name: string;
  arguments: unknown;
}
// ↑ src/shared/event-log.ts

export interface Message {
  role: Role;
  content: string;
  /** User messages may attach pixels. Omitted from logged conversation; used on one-shot judge calls. */
  images?: MessageImage[];
  /** Assistant messages may carry tool calls. */
  tool_calls?: ToolCall[];
  /** Tool messages carry the id of the call they answer. */
  tool_call_id?: string;
  /** A tool message whose call failed: engines that mark failures tell the model so. */
  is_error?: boolean;
  /** Optional reasoning trace (kept out of the prompt by default). */
  reasoning?: string;
  name?: string;
}
// ↑ src/shared/event-log.ts

export interface ToolDefinition {
  name: string;
  description: string;
  /** JSON Schema. pi-ai types this as typebox's TSchema, which is a JSON Schema at runtime. */
  parameters: Record<string, unknown>;
}
// ↑ src/shared/engine-requests.ts

/** Request settings whose capabilities are advertised by the selected provider/model. */
export interface ModelPreferences {
  fast?: boolean;
}
// ↑ src/shared/model-preferences.ts

export type CompletionRole = 'judge' | 'playtester' | 'skillopt-gate';
// ↑ src/shared/custom-events.ts

/**
 * What a caller of `engine.complete` says about its call, for the record only: never sent to the
 * model. `promptSha256` is the SHA-256 of the system prompt (the rubric, no evidence).
 */
export interface CompletionProvenance {
  role?: CompletionRole;
  runId?: string;
  fellBack?: boolean;
  promptSha256?: string;
}
// ↑ src/shared/custom-events.ts

/** What `engine.complete` takes: a completion request's serializable half plus the routing fields. */
export interface HarnessCompleteParams {
  messages: Message[];
  model?: string;
  systemPrompt?: string;
  tools?: ToolDefinition[];
  maxTokens?: number;
  temperature?: number;
  effort?: string;
  preferences?: ModelPreferences;
  timeoutMs?: number;
  /** Direct engine id; `ollama` when omitted. */
  engine?: string;
  /** `false` is a reviewer's call: no stream to the chat and no stream events. */
  stream?: boolean;
  threadId?: string;
  class?: HarnessWorkClass;
  toolRegistryRevision?: number;
  /** Who asked and why, for the call's `completion_call` record only: never sent to the model. */
  provenance?: CompletionProvenance;
}
// ↑ src/shared/harness-api.ts

/** A studio tool in the flat shape a delegated engine exposes: string-typed properties only. */
export interface StudioToolSpec {
  name: string;
  description: string;
  parameters: {
    type: "object";
    properties: Record<string, { type: string; description?: string }>;
    required?: string[];
  };
}
// ↑ src/shared/engine-requests.ts

export type PreviewInputAction =
  /** `stepMs` advances the page's own loop between the press and the release, so a game that reads a key inside its frame sees it held (M4.1). It is honoured only while the studio owns the clock. */
  | { type: "tap"; keys: string[]; stepMs?: number }
  | { type: "down"; keys: string[] }
  | { type: "up"; keys: string[] }
  | { type: "hold"; keys: string[]; ms?: number }
  /** `px: true` reads x/y as pixels even when both fall in 0…1; `clicks` 2 = double, 3 = triple; `modifiers` are held for the click; `stepMs` is the tap's, for the press-to-release gap. */
  | {
      type: "click";
      x?: number;
      y?: number;
      button?: "left" | "right" | "middle";
      clicks?: number;
      modifiers?: string[];
      px?: boolean;
      stepMs?: number;
    }
  | { type: "move"; x: number; y: number; px?: boolean }
  /** Press at (fromX, fromY), glide to (x, y), release — a drag the way a player does it. */
  | {
      type: "drag";
      fromX: number;
      fromY: number;
      x: number;
      y: number;
      button?: "left" | "right" | "middle";
      px?: boolean;
    }
  | { type: "mousedown"; button?: "left" | "right" | "middle" }
  | { type: "mouseup"; button?: "left" | "right" | "middle" }
  | { type: "look"; dx: number; dy: number }
  /** Wheel at the pointer, or at (x, y) in pixels when given. */
  | { type: "scroll"; dx?: number; dy?: number; x?: number; y?: number }
  /** Type literal text: one keydown/char/keyup per character, the way a keyboard delivers it. */
  | { type: "type"; text: string }
  /** One key or a `+`-joined chord ("ctrl+s", "shift+Return"), `repeat` times. */
  | { type: "press"; combo: string; repeat?: number }
  | { type: "wait"; ms: number };
// ↑ src/shared/preview-contract.ts

/**
 * The state a run is about, reached the way a player reaches it, after every load and before
 * anyone looks: the scout writes it (a key that opens the map picker, the click on the map,
 * a demo that does the same), the harness applies it before judges, captures and the computer
 * tool's first frame. `verify` is a probe over `__studio.state()` that says the state landed —
 * without it a run can build and judge the wrong map for hours because nothing checked.
 */
export interface PreviewSetup {
  /**
   * Knock first: a trusted move + click (and optional key tap) before anything else runs, at
   * the view centre or a placed point. It is what grants user activation, so a title screen
   * that waits for a click, a pointer lock and an AudioContext all get what they are waiting
   * for. `true` takes the centre.
   */
  gesture?: true | { x?: number; y?: number; keys?: string[] };
  /** Input actions in order (tap, hold, click, wait …), capped like any script. */
  actions?: PreviewInputAction[];
  /** A `config.demos` entry that reaches the state deterministically — preferred when it exists. */
  demo?: string;
  /** Milliseconds to let the game settle after the script; default 400. */
  settleMs?: number;
  /** A dotted state path and the value it must hold (`equals`), or merely be truthy. */
  verify?: { path: string; equals?: unknown; truthy?: boolean };
  /** One sentence for the log and the briefs: what this reaches and why. */
  note?: string;
  /**
   * A game that reports a front-end (`state().flow.playing === false`) is put into play with
   * `__studio.begin()` by default: by a studio window before the setup is replayed (the scout
   * recorded it in play), by the evidence pass after its seed. `false` keeps its title, menu or
   * countdown on screen for the worker that builds them; the playtester's window always does.
   */
  begin?: boolean;
}
// ↑ src/shared/preview-contract.ts

/** Builder eyes: the serializable capture grant for the workspace a delegation builds in. */
export interface DelegateCaptureGrant {
  project: string;
  root: string;
  runId?: string;
  facetId?: string;
  iteration?: number;
  handle?: string;
  entry?: string;
  setup?: PreviewSetup | null;
  label?: string;
  /** The worker's own cameras: what a capture that names none photographs (every registered camera when absent). */
  cameras?: string[];
}
// ↑ src/shared/engine-requests.ts

/** Playtester hands: the serializable half of the live preview tools over the build under test. */
export interface DelegatePlaytestGrant {
  project: string;
  root: string;
  runId?: string;
  facetId?: string;
  iteration?: number;
  handle?: string;
  entry?: string;
  setup?: PreviewSetup | null;
  role?: "playtester" | "scout";
  label?: string;
}
// ↑ src/shared/engine-requests.ts

/** A still that goes into the builder's prompt as an image block. */
export interface DelegateImage {
  label: string;
  mimeType: string;
  data: string;
}
// ↑ src/shared/engine-requests.ts

/**
 * Edit-time file ownership: the engine blocks Write/Edit outside `owns` (plus the facet's notes
 * and the wiring line of src/main.js) before the edit lands. See `DelegateRequest.ownership`.
 */
export interface DelegateOwnership {
  facetId: string;
  owns: string[];
  ownsMain: boolean;
  main?: string;
  studio?: string;
  template?: boolean;
  neverLock?: string[];
}
// ↑ src/shared/engine-requests.ts

/**
 * The director's session: the run's integration worktree it orchestrates from (`root`). A waking
 * run's lead sits in the game folder instead and leads `root`, leaving the game's changes to its
 * workers: the host honours its grant only with `readOnly`, for this game's own run, and hands the
 * engine `root`'s checked real path (delegation.ts `#leadRoot`).
 */
export interface DelegateDirectorGrant {
  runId: string;
  threadId: string;
  project: string;
  root: string;
  setup?: PreviewSetup | null;
  /**
   * The lead IS its chat's own session (one session): the session it answers with becomes the
   * chat's bookmark (`contractor`), so the chat goes on in it after the run. Honoured only for a
   * lead in its game's folder.
   */
  chatSession?: boolean;
}
// ↑ src/shared/engine-requests.ts

/** A live studio tool: the flat projection, plus the real schema when the flat one cannot say it. */
export interface LiveToolSpec extends StudioToolSpec {
  /**
   * The tool's real JSON Schema, when it has one the flat `parameters` cannot express — an MCP
   * connector's arrays, enums, integers and nested objects. Authoritative when present;
   * `parameters` stays the flat projection every older consumer still reads. Studio's own live
   * tools and plugin tools are flat and never set it.
   */
  inputSchema?: Record<string, unknown>;
}
// ↑ src/shared/engine-requests.ts

/**
 * What the harness asks for when it starts a worker: its id and title, the run or the chat turn it
 * belongs to, and whether it may search the web as a reader. Honoured only by the host's own
 * finding; a grant it cannot confirm leaves the session unattended.
 */
export interface WorkerGrant {
  id: string;
  title: string;
  /** The run whose lead started it: a run started in this game's open chat, still running. */
  runId?: string;
  /** The chat message whose turn started it: the one the chat's own session answers now. */
  turn?: string;
  /** It may search and read the web even as a reader. */
  research?: boolean;
}
// ↑ src/shared/workers.ts

/** What `engine.delegate` takes: a delegation's serializable half plus the routing fields. */
export interface HarnessDelegateParams {
  coordinator?: { runId: string; messageId?: string };
  /**
   * The chat's own session after a run it led: the run's controls it keeps (`run_status`,
   * `show_build`, `land_build`, shared/coordinator.ts `RunControl`), answered by the host for this
   * run and message as the coordinator's tools are. Honoured only for the chat's own session.
   */
  runControls?: { runId: string; messageId?: string };
  /**
   * This session is its chat's current turn: the message it answers. What the person sends
   * meanwhile can reach it (`engine.steer`); honoured only for the chat's own session, and for a
   * run's lead (a `director` session), whose turn is named by its run id instead.
   */
  chatTurn?: { messageId?: string };
  engine?: string;
  prompt: string;
  project: string;
  /** Build here instead of the live game folder — a facet worktree under scratch. */
  cwd?: string;
  threadId?: string;
  model?: string;
  effort?: string;
  preferences?: ModelPreferences;
  maxTurns?: number;
  timeoutMs?: number;
  resume?: string;
  /** Compact the `resume` session with its provider's own compaction instead of a turn (`EngineDescriptor.compactsNatively`). */
  compact?: boolean;
  extraReads?: string[];
  class?: HarnessWorkClass;
  /** A Loop chat's launch tool and `ask_user`, bridged to the contractor (MCP for Claude, the bridge for Codex). */
  interviewTools?: StudioToolSpec[];
  /** Builder eyes: capture-tool grant for the workspace this delegation builds in. */
  selfCapture?: DelegateCaptureGrant;
  /** Playtester hands: live preview tools over the build under test; implies read-only. */
  playtest?: DelegatePlaytestGrant;
  readOnly?: boolean;
  /** Stills into the builder's prompt. */
  images?: DelegateImage[];
  /** Edit-time ownership the engine enforces before a Write lands. */
  ownership?: DelegateOwnership;
  /** The computer: `false` withholds the builder's hands; default on with a capture grant. */
  computer?: boolean;
  /** The director: the run's orchestrating session, with the harness's run tools forwarded. */
  director?: DelegateDirectorGrant & { tools?: LiveToolSpec[] };
  /**
   * A run's sub-agent: every plugin call this session makes carries the run and the agent's id (its
   * part id, recorded as `facetId`), so what it makes is recorded under that run and lands on the
   * agent's own node in the Builds graph.
   */
  attribution?: { runId: string; agentId: string };
  /**
   * Plugin tool and connector names (or name prefixes, such as `blender__`) this session may use:
   * a tool whose agent name starts with none of them is not offered; a plugin with an offered tool
   * also keeps its skill reader `<plugin>__skill` and its guidance. Absent, every tool is offered.
   */
  toolAllow?: string[];
  /**
   * The Genex credits the paid jobs of this session's run (its `attribution` or `director` run) may
   * commit, counted across every session of the run: once they have, the run's next paid Genex job
   * is refused before Genex is asked. Anything but a whole number allows none; absent, no cap.
   */
  creditCap?: number;
  candidateId?: string;
  /**
   * A worker of a chat's lead: honoured only by the host's own finding (a running run started in
   * this game's open chat, or the chat turn its own session answers now), and then run in the
   * chat's permission mode, asking in the chat. A grant the host cannot confirm runs unattended.
   */
  worker?: WorkerGrant;
  /**
   * The worker tools the chat's own session may call (`WorkerTool`), answered by the harness's pool
   * for this turn (`worker_tool`). Honoured only for the chat's own session answering a chat turn,
   * on a harness that claims `workers`, and never for a worker: depth is one.
   */
  workers?: { tools?: LiveToolSpec[] };
}
// ↑ src/shared/harness-api.ts

export interface AssetAvailability {
  assetId: string;
  generationId?: string;
  originalAvailable: boolean;
  deliveries: Array<{
    workspaceId: string;
    scope: "project" | "integration" | "worker";
    relativePath: string;
    present: boolean;
    revision?: string;
  }>;
  usage: "unverified" | "observed" | "verified";
}
// ↑ src/shared/game-assets.ts

export type AssetKind = "image" | "model" | "audio" | "video" | "other";
// ↑ src/shared/game-assets.ts

/** `genex` and `blender` are the two the studio ships; any other value is a plugin id. */
export type AssetSource = "genex" | "blender" | "imported" | (string & {});
// ↑ src/shared/game-assets.ts

export interface ProjectAsset {
  availability?: AssetAvailability;
  /** Host-issued reference for a retained original; never an arbitrary root. */
  assetRef?: string;
  variants?: Array<{ role: string; url: string; bytes?: number }>;
  preferredFile?: string;
  derivedFrom?: string;
  file: string;
  kind: AssetKind;
  bytes: number;
  mtime: string;
  source: AssetSource;
  jobId?: string;
  generationId?: string;
  operation?: string;
  prompt?: string;
  /**
   * The plugin's own word for the job that made this file (`downloaded`, `failed`,
   * `retrieval_failed`, …). Where the file is lives in `availability`; neither is a sentence.
   */
  pluginStatus?: string;
  at?: string;
  /** Evidence a plugin recorded about the file being loaded by the running game — an observation, never proof. */
  use?: { stage: "unconfirmed" | "integrated" | "verified"; inspectionId?: string; observedAt?: string };
  /** Absolute path of a render PNG under the run folder, readable through `readRunStill`. */
  render?: string | null;
  renderFront?: string | null;
  runId?: string;
  facetId?: string;
  iteration?: number;
}
// ↑ src/shared/game-assets.ts

export interface ProjectAssets {
  project: string;
  assets: ProjectAsset[];
  /**
   * Jobs with no file in the game yet: the plugin's own word for each (`pluginStatus`), and
   * `delivered` when the job did deliver files earlier that the game no longer holds.
   */
  jobs?: Array<{
    source: string;
    jobId: string;
    at?: string;
    operation?: string;
    prompt?: string;
    pluginStatus?: string;
    delivered?: boolean;
  }>;
  /** The walk hit its entry or depth cap: some files under `assets/` are not listed. */
  truncated: boolean;
  skipped: Array<{ file: string; why: string }>;
}
// ↑ src/shared/game-assets.ts

/** One model's share of a session, in `Usage`'s units (a row of Claude's `modelUsage`). */
export interface ModelTokenUsage {
  input_tokens: number;
  output_tokens: number;
  cache_read_tokens: number;
  cache_write_tokens: number;
  /** Thinking tokens, already inside `output_tokens`; absent when the CLI did not record them. */
  reasoning_tokens?: number;
  cost_usd?: number;
  context_window?: number;
}
// ↑ src/shared/event-log.ts

/**
 * What one engine call used. The token fields are the session's main loop (Claude's
 * `result.usage`, per turn and added up; a Codex turn's usage); every other model it called is in
 * `by_model`. `output_tokens` counts everything the model produced, its reasoning included, so
 * `reasoning_tokens` is a part of it and is never added again. `input_tokens` keeps the
 * provider's own meaning: Anthropic's excludes cache reads, Codex's (OpenAI's) includes them.
 * A figure the provider did not report is absent, never zero.
 */
export interface Usage {
  input_tokens?: number;
  output_tokens?: number;
  cache_read_tokens?: number;
  cache_write_tokens?: number;
  /** Thinking or reasoning tokens, already counted inside `output_tokens`. */
  reasoning_tokens?: number;
  cost_usd?: number;
  model?: string;
  engine?: string;
  /**
   * Every model the session called — main loop, subagents, compaction and auxiliary calls —
   * keyed by the id the CLI reported, as its running total (Claude's `modelUsage`).
   */
  by_model?: Record<string, ModelTokenUsage>;
  /** Time the provider's API spent answering, as the latest result reports it (Claude's `duration_api_ms`). */
  duration_api_ms?: number;
  /** Time to the first token of the session's first reply (Claude's `ttft_ms`). */
  ttft_ms?: number;
  /** Context compactions the session went through during this call. */
  compactions?: number;
}
// ↑ src/shared/event-log.ts

export type MessageUsageSource = 'delegation';
// ↑ src/shared/event-log.ts

export type SnapshotScope = 'game' | 'harness' | 'both';
// ↑ src/shared/event-log.ts

export interface SnapshotGitRefs {
  game?: string;
  harness?: string;
  /**
   * The branch a game snapshot was taken on (`refs/heads/…`), `null` when HEAD was detached,
   * absent on harness-only and older records. A game restore refuses when it moved.
   */
  gameBranch?: string | null;
}
// ↑ src/shared/event-log.ts

export type EventData =
  | { type: "thread_created"; title?: string; metadata?: Record<string, unknown> }
  | { type: "thread_updated"; title?: string; metadata?: Record<string, unknown> }
  | { type: "thread_deleted" }
  | { type: "thread_forked"; source_thread_id: string; up_to_inclusive: string }
  | { type: "session_started"; metadata?: Record<string, unknown> }
  | { type: "session_ended"; reason?: string }
  | { type: "turn_started"; metadata?: Record<string, unknown> }
  | { type: "turn_ended"; status?: "ok" | "error" | "cancelled"; metadata?: Record<string, unknown> }
  | {
      type: "messages";
      messages: Message[];
      usage?: Usage;
      /** Whose engine call `usage` reports when it is not the chat's own: absent on the chat's own calls and older records. */
      usage_source?: MessageUsageSource;
    }
  | { type: "tool_requested"; tool_call_id: string; request: { name: string; arguments: unknown } }
  | {
      type: "tool_result";
      tool_call_id: string;
      result: { ok: boolean; content: string; details?: unknown };
    }
  | { type: "error"; message: string; details?: unknown }
  | { type: "artifact_written"; artifact_id: string; path: string; version: number }
  | {
      type: "snapshot_created";
      snapshot_id: string;
      scope: SnapshotScope;
      git: SnapshotGitRefs;
      healthy?: boolean;
      /** False when `healthy` vouches for the game half only (see `SnapshotRecord.harness_healthy`). */
      harness_healthy?: false;
      reason?: string;
    }
  | {
      type: "workspace_restored";
      snapshot_id: string;
      reason: string;
      scope: SnapshotScope;
      /** The rescue snapshot of the game folder, committed just before the folder was reset. */
      rescue_snapshot_id?: string;
    }
  | { type: "custom"; event_type: string; payload?: unknown };
// ↑ src/shared/event-log.ts

export interface EventEnvelope {
  id: string;
  thread_id: string;
  session_id: string | null;
  turn_id: string | null;
  created_at: string;
  data: EventData;
}
// ↑ src/shared/event-log.ts

export interface ConversationRecord {
  id: string;
  agent_id: string;
  created_at: string;
  updated_at: string;
  /** Optimistic-concurrency head. `null` until the first event lands. */
  latest_event_id: string | null;
  title?: string;
  /** Present on forks. */
  parent?: { thread_id: string; up_to_inclusive: string } | null;
  metadata?: Record<string, unknown>;
}
// ↑ src/shared/event-log.ts

/** Durable, additive Optimization stage JSON. Page observations never supply revision identity. */
export interface Revision {
  snapshotId: string | null;
  commit: string;
  tree: string;
}
// ↑ src/shared/optimization.ts

/** A host-owned optimizer worktree (`substrate/game-candidate.ts`), as `optimization.open` answers it. */
export interface OptimizationCandidate {
  candidateId: string;
  project: string;
  runId: string;
  root: string;
  baselineRoot: string;
  baseline: Revision;
  frozen: Revision | null;
  closed: boolean;
}
// ↑ src/shared/optimization.ts

/**
 * One entry of the snapshot index (`substrate/snapshots.ts`): the commits a snapshot holds, plus —
 * for a game — the branch it was taken on (`SnapshotGitRefs.gameBranch`). It rides inside `git` so
 * the `snapshot_created` event carries it and a rebuilt index still has it.
 */
export interface SnapshotRecord {
  snapshot_id: string;
  scope: SnapshotScope;
  git: SnapshotGitRefs;
  created_at: string;
  reason: string;
  healthy: boolean;
  /**
   * False when `healthy` speaks for the game half only: a "both" snapshot of a won round holds a
   * harness nobody has booted yet, and the watchdog must not rewind to it (R2). Marking the
   * record healthy later (a restart, an inherited non-code diff) vouches for both halves.
   */
  harness_healthy?: false;
}
// ↑ src/shared/event-log.ts

export interface PluginTool {
  name: string;
  description: string;
  parameters: {
    type: "object";
    properties: Record<string, { type: string; description?: string; acceptJsonString?: boolean }>;
    required?: string[];
  };
  /** API 2: an agent-invoked tool that needs the user's consent before it runs. */
  confirmation?: string;
}
// ↑ src/shared/plugins.ts

/**
 * A tool a plugin offers that makes a kind of project (its manifest's `makes`), as a session's
 * snapshot lists it: the plugin's id and name, the tool's agent name `<plugin>__<tool>`, and the
 * facts. `asksReady` says the tool declares a `ready` harness tool (a plugin's new-game tool, the
 * one its engine card offers). For a game with no kind yet, the host fills `ready` and `note` from
 * that tool (whether one can be made here now, and the words the engine card offers it with); both
 * are absent when it declares none or its answer didn't come.
 */
export interface PluginKindOffer {
  plugin: string;
  name: string;
  tool: string;
  makes: string[];
  asksReady?: boolean;
  ready?: boolean;
  note?: string;
}
// ↑ src/shared/plugins.ts

export type WorkerIsolation = 'read' | 'copy' | 'lock';
// ↑ src/shared/workers.ts

/**
 * A kind of worker a plugin declares (`PluginManifest.workerTypes`), as the registry hands it to a
 * lead: `tools` are agent names (`<plugin>__<tool>`) or name prefixes (`<plugin>__`) a worker of
 * this kind is offered.
 */
export interface WorkerType {
  pluginId: string;
  id: string;
  description: string;
  tools: string[];
  isolation: WorkerIsolation;
}
// ↑ src/shared/workers.ts

export type PluginOffer = 'turn-on' | 'install';
// ↑ src/shared/project-tools.ts

/** One Genex plugin `plugins_find` found: `offer` absent when it is on already; `facts` it detects, serves or makes. */
export interface PluginFound {
  id: string;
  name: string;
  description: string;
  offer?: PluginOffer;
  facts: string[];
}
// ↑ src/shared/project-tools.ts

export type FindNext = 'suggest' | 'use' | 'write-plugin';
// ↑ src/shared/project-tools.ts

/** What `plugins_find` answers: the plugins found (on, then off, then Genex's catalog), what to do next, and a note. */
export interface PluginsFindAnswer {
  plugins: PluginFound[];
  next: FindNext;
  note: string;
}
// ↑ src/shared/project-tools.ts

/** What `plugins_suggest` answers: whether the card was shown, and what the session is told. */
export interface PluginsSuggestAnswer {
  shown: boolean;
  message: string;
}
// ↑ src/shared/project-tools.ts

/** A connector tool as an engine sees it: the flat projection plus the schema it came from. */
export interface McpLiveTool {
  name: string;
  description: string;
  parameters: {
    type: "object";
    properties: Record<string, { type: string; description?: string }>;
    required?: string[];
  };
  inputSchema: Record<string, unknown>;
}
// ↑ src/shared/mcp.ts

/**
 * What a live tool answers: text, and for the computer tool's screenshot/zoom the picture
 * itself — an MCP result carries image blocks; the Codex bridge prints the saved path.
 */
export type LiveToolResult =
  | string
  | {
      text: string;
      images?: Array<{ mimeType: string; data: string; label?: string }>;
      /** The call failed: an engine that marks failures tells the model so. */
      isError?: boolean;
    };
// ↑ src/shared/engine-requests.ts

export type HookHold = 'plan' | 'person_first' | 'cant_tell' | 'busy';
// ↑ src/shared/plugin-hooks.ts

/** What held a moment back, beside its reason: Genex's hold and the lock's label, when it was Genex's. */
export interface HookHeld {
  hold?: HookHold;
  label?: string;
}
// ↑ src/shared/plugin-hooks.ts

/** A picture a handler hands back (a base64 PNG), with any numbers it measured. */
export interface HookImage {
  name: string;
  data: string;
  measures?: Record<string, number>;
}
// ↑ src/shared/plugin-hooks.ts

/** What a moment's handlers answered: the first block, the first pending, every note and picture, and who ran (agent names, in order). */
export interface HookReport {
  blocked: ({ plugin: string; tool: string; reason: string } & HookHeld) | null;
  pending: { plugin: string; reason: string } | null;
  notes: Array<{ plugin: string; text: string }>;
  images: HookImage[];
  ran: string[];
}
// ↑ src/shared/plugin-hooks.ts

export type CheckpointSkip = 'cant_tell' | 'nothing_unsaved';
// ↑ src/shared/plugin-hooks.ts

/**
 * What a checkpoint answers: the snapshot it took with its handlers' notes and pictures; why a
 * handler, a lock or Plan mode stopped it (no snapshot; `hold` when it was Genex's); or why one
 * asked only if something is unsaved was skipped.
 */
export type CheckpointAnswer =
  | { snapshot: SnapshotRecord; notes: HookReport["notes"]; images: HookImage[] }
  | ({ blocked: string } & HookHeld)
  | { skipped: CheckpointSkip; reason: string };
// ↑ src/shared/plugin-hooks.ts

export type HookEvent = 'run.prepare' | 'run.end' | 'turn.start' | 'turn.end' | 'checkpoint.before' | 'checkpoint.after' | 'restore.before' | 'restore.after' | 'worker.start' | 'worker.end' | 'tool.before' | 'tool.after' | 'health' | 'crash' | 'finish';
// ↑ src/shared/plugin-hooks.ts

export type EngineKind = 'direct' | 'delegated';
// ↑ src/shared/engine-descriptor.ts

export type EngineStatusCode = 'ready' | 'not_installed' | 'not_running' | 'needs_login' | 'error';
// ↑ src/shared/engine-descriptor.ts

export interface EngineStatus {
  code: EngineStatusCode;
  detail: string;
  /** What the UI should offer to do about it. */
  remedy?: string;
}
// ↑ src/shared/engine-descriptor.ts

/** Sanitized account usage. It never contains account identifiers or credentials. */
export interface ProviderUsage {
  measuredAt: string;
  plan?: string;
  windows: Array<{ id: string; label: string; percent: number | null; resetsAt?: string }>;
}
// ↑ src/shared/provider-usage.ts

export type ModelCatalogState = 'ready' | 'loading' | 'stale' | 'unavailable';
// ↑ src/shared/model-catalog.ts

export type ModelCatalogSource = 'provider' | 'cache';
// ↑ src/shared/model-catalog.ts

export type ModelCatalogProblemCode = 'provider' | 'timeout' | 'unsupported' | 'malformed';
// ↑ src/shared/model-catalog.ts

/** Serializable catalog progress for Settings and the model picker. */
export interface ModelCatalogStatus {
  state: ModelCatalogState;
  revision: number;
  refreshing: boolean;
  source?: ModelCatalogSource;
  refreshedAt?: number;
  problem?: { code: ModelCatalogProblemCode; message: string };
}
// ↑ src/shared/model-catalog.ts

export type CodingProvider = "codex" | "claude-code" | "opencode";
// ↑ src/shared/coding-cli.ts

export interface CodingCliStatus {
  provider: CodingProvider;
  state: "ready" | "missing" | "invalid_path" | "missing_runtime" | "incompatible";
  selection: "automatic" | "manual";
  path?: string;
  version?: string;
  detail: string;
  guidanceUrl: string;
}
// ↑ src/shared/coding-cli.ts

/** Subscription engines only: which login Studio uses and the state of the external CLI. */
export interface EngineAccount {
  /** env: a variable decides; isolated: Studio's own login; system: the CLI's own login, as used in Terminal. */
  source: "env" | "isolated" | "system" | "none";
  /** The environment variable that decides the login when `source` is env. */
  variable?: string;
  /** What signing out of Studio's own login leaves: the Terminal login, or no connection. */
  afterSignOut: "terminal" | "signed-out";
  cli: { state: CodingCliStatus["state"]; version?: string; path?: string };
}
// ↑ src/shared/engine-descriptor.ts

/**
 * How a provider signs in: Claude through a piped or embedded terminal plus status polling, Codex
 * through its native login reported from the in-app console, OpenCode through its own `auth login`
 * in the embedded terminal (which keeps every provider it signs in to), `none` for an engine with
 * no sign-in of its own (a local model, or OpenRouter, whose key is pasted in Settings).
 */
export type LoginKind = "terminal" | "console" | "cli" | "none";
// ↑ src/shared/providers.ts

/**
 * Which roles a provider can run: `presets` has the model rows and single-pick presets of
 * `shared/model-roles.ts`, `sessions` can cross roles without presets, `completion` gives each
 * job its own model without sessions (its reviewers may join a session run, its main agent may
 * hand its jobs to one), and `single` runs one model.
 */
export type RoleSupport = "presets" | "sessions" | "completion" | "single";
// ↑ src/shared/providers.ts

/**
 * Who pays for a provider's work: nobody (`local`), a plan the person already has
 * (`subscription`, throttled server-side, never billed per call), or per token (`metered`). A
 * choice the app makes on its own — a fallback, a first ready engine — never lands on a metered
 * provider: only the person's explicit pick spends their credits.
 */
export type Billing = "local" | "subscription" | "metered";
// ↑ src/shared/providers.ts

/** What the sign-in card and the Models room say for a subscription. */
export interface SignInCopy {
  /** "your Claude subscription": the thing the user already pays for. */
  readonly product: string;
  readonly card: string;
  readonly account: string;
  readonly install: string;
  /** The vendor's own install page for the CLI. */
  readonly installUrl: string;
  readonly get: string;
  readonly who: string;
}
// ↑ src/shared/providers.ts

export interface ProviderInfo {
  /** The engine id (`Engine.id`). */
  readonly id: string;
  /** The provider's name as a person says it. */
  readonly label: string;
  readonly subscription: boolean;
  readonly login: LoginKind;
  readonly roles: RoleSupport;
  readonly billing: Billing;
  /** Subscriptions only. */
  readonly signIn: SignInCopy | null;
}
// ↑ src/shared/providers.ts

export interface EngineDescriptor {
  id: string;
  label: string;
  kind: EngineKind;
  supportsSessions?: boolean;
  /** Compacts a session in place with the provider's own compaction (Claude Code, Codex). */
  compactsNatively?: boolean;
  status: EngineStatus;
  usage?: ProviderUsage | null;
  catalog?: ModelCatalogStatus;
  account?: EngineAccount | null;
  /** The provider table's row for this engine (`shared/providers.ts`); null for an unlisted engine. */
  provider?: ProviderInfo | null;
  models: Array<{
    id: string;
    label: string;
    resolvedModel?: string;
    /** The model the provider's catalog names as its default; the picker lists it for "default". */
    providerDefault?: boolean;
    contextWindow: number;
    supportsFast?: boolean;
    supportsTools: boolean;
    supportsVision: boolean;
    stale?: boolean;
    /** A short alias the CLI resolves to another listed model, so pickers list that model once. */
    aliasOf?: string;
    note?: string;
    /** What the composer's effort menu offers for this model; empty = no effort dial. */
    efforts?: string[];
    defaultEffort?: string;
  }>;
  defaultModel: string | null;
}
// ↑ src/shared/engine-descriptor.ts

export interface StudioSettingsView {
  /** Self-improvement: off, Studio learns nothing new and changes nothing about itself. */
  learning: boolean;
  /** Apply suggestions automatically, while learning is on. */
  selfImproving: boolean;
  architect?: boolean;
  /** Maximum builders a run may use at once; the lead decides how many it starts. */
  buildersMax?: number;
  agentsMax?: number;
  /** may builders model in Blender (AG-930); on by default */
  blender?: boolean;
  /** Resume builds automatically after an engine limit resets or the loop restarts; on by default. */
  autoResume?: boolean;
}
// ↑ src/shared/studio-api.ts

/**
 * What a run's outcome is, as data: where the run stands, what became of its build, and whether
 * the checks on that build need attention. `renderer/words.ts` (`outcomeTitle`) says it — once
 * per surface, from these three fields, instead of each surface rewriting one English sentence.
 */
export interface OutcomeView {
  state: "unknown" | "running" | "paused" | "failed" | "cancelled" | "finished";
  /**
   * `delivered`: the build is in the game. `superseded`: a build was delivered, but a newer
   * integrated build was not. `available`: an integrated build exists that was not delivered
   * (yet). `none`: nothing to show.
   */
  delivered: "delivered" | "superseded" | "available" | "none";
  /** The checks recorded on the current build: one failed, or they are incomplete. */
  verification: "attention" | "incomplete";
}
// ↑ src/shared/run-summary.ts

/** What a run left the user with, in the words Activity shows. */
export type RunOutcomeKind = "running" | "delivered" | "none" | "failed" | "stopped" | "unknown";
// ↑ src/shared/studio-activity.ts

export interface StudioActivityItem {
  id: string;
  at: string;
  /** `recovery` and `upkeep` are Studio looking after itself; neither is a result for the user. */
  kind: "run" | "improvement" | "learning" | "recovery" | "upkeep";
  title: string;
  /** A learned change's own state (`Undone`, `2 awaiting review`); a run has `runOutcome` instead. */
  status?: string;
  /** Where a run stands, as fields; the renderer words it (`outcomeTitle` in renderer/words.ts). */
  runOutcome?: OutcomeView;
  detail: string;
  attention?: boolean;
  project?: string;
  runId?: string;
  snapshotId?: string;
  undone?: boolean;
  outcome?: RunOutcomeKind;
  /** The run's own plain report, when it wrote one. */
  report?: string;
  /** Plain lines describing an instruction change, and who let it land. */
  summary?: string[];
  approvedBy?: "auto" | "human";
}
// ↑ src/shared/studio-activity.ts

/** Context is scoped to a selected provider/model and a specific measured session. */
export interface ContextPolicy {
  mode: "default" | "custom";
  thresholdPercent?: number;
}
// ↑ src/shared/context.ts

export interface ContextSettings {
  policy: ContextPolicy;
  inherited: boolean;
  owner: "provider" | "studio";
  configurable: boolean;
  reason?: string;
  defaultPercent?: number;
}
// ↑ src/shared/context.ts

export interface CompleteResponse {
  /** Assistant message (with any tool calls), ready to be appended to the log verbatim. */
  message: Message;
  usage: Usage;
  stopReason: string;
  model: string;
  engine: string;
}
// ↑ src/shared/engine-requests.ts

export interface DelegateResult {
  requestedModel?: string;
  cliVersion?: string;
  cliPath?: string;
  ok: boolean;
  summary: string;
  usage: Usage;
  turns: number;
  engine: string;
  /** The model that actually ran, as the contractor reported it — not just what was asked for. */
  model?: string;
  durationMs?: number;
  /** Why a not-ok build ended: "stopped" (user), "deadline" (time budget), or the vendor's own subtype (e.g. error_max_turns). */
  stopReason?: string;
  /** Vendor session id — what `resume` takes to continue exactly where this build ended. */
  sessionId?: string;
  /** "subscription" usage is prepaid quota — cost_usd is then API-equivalent, not a bill. */
  billing?: "subscription" | "api";
  /** The vendor's own words for a not-ok ending, for the chat message. */
  errorText?: string;
  /** Calls the contractor made to `interviewTools`, in order — the harness executes them for real. */
  studioToolCalls?: Array<{ name: string; args: Record<string, unknown> }>;
  /** Steered messages the session read (`DelegateRequest.steer`), by id, in the order it read them. */
  steered?: string[];
  /**
   * How many tokens the session's last request sent, as the provider counted them: what its next
   * turn starts from. Absent when the provider reported none, or compacted after its last request.
   */
  contextTokens?: number;
  /** A `compact` delegation compacted the session, which goes on under the same id. */
  compacted?: boolean;
}
// ↑ src/shared/engine-requests.ts

/** A message the person sent while the chat's turn works, handed into that turn (steer). */
export interface SteerMessage {
  /** The queue's message id: what the delivery is recorded under. */
  id: string;
  text: string;
  images?: DelegateImage[];
}
// ↑ src/shared/engine-requests.ts

export type SteerDelivery = 'prompt' | 'native' | 'interrupt' | 'lead';
// ↑ src/shared/message-queue.ts

/** One catalog model judged against this Mac (Settings → Local Models). */
export interface LocalModelChoice {
  model: string;
  name: string;
  variant?: string;
  engine?: string;
  sizeGb: number;
  tools: boolean;
  vision: boolean;
  about: string;
  fits: boolean;
  needGb: number;
  needsRamGb: number | null;
  reason: string;
}
// ↑ src/shared/studio-api.ts

/** This Mac's hardware and the local models it can run (`StudioApi.hardware`, harness `engine.hardware`). */
export interface HardwareReport {
  hardware: { cpu: string; ramGb: number; usableModelGb: number };
  recommendation: {
    tier: { label: string; expectation: string };
    defaultModel: string | null;
    /** The tier's ranked models that fit; the first is Best fit. */
    picks: LocalModelChoice[];
    /** Every other model this Mac can run, smallest first, fitting or not. */
    more: LocalModelChoice[];
  };
}
// ↑ src/shared/studio-api.ts

/** Host-owned presentation metadata. Folder identity and game files never change on rename. */
export type CoverStyle = "world" | "relic" | "city";
// ↑ src/shared/game-library.ts

export type LegacyShaderCover = {
  kind: "shader";
  version: 1 | 2;
  surface: string;
  seed: number;
  poster: string;
  custom: boolean;
};
// ↑ src/shared/game-library.ts

/** A family whose looks are named palettes, drawn by the shared sphere program. */
export type PaletteFamily = 'aurora' | 'clouds' | 'bands' | 'marble' | 'ember' | 'ocean';
// ↑ src/shared/cover-recipe.ts

export type OrbFamily = 'orbital' | 'bricks' | 'plasma' | 'pixel' | 'caustic' | 'tempest' | 'nimbus' | 'terminal' | 'voxel' | 'meadow' | 'galaxy' | 'thermal';
// ↑ src/shared/cover-recipe.ts

export type CoverFamily = PaletteFamily | OrbFamily;
// ↑ src/shared/cover-recipe.ts

export type CoverRecipe = {
  kind: "recipe";
  family: CoverFamily;
  /** A palette family's named palette; absent for orb families. */
  palette?: string;
  /** An orb family's hue slot, 0 to COVER_HUE_SLOTS − 1; absent for palette families. */
  hue?: number;
  seed: number;
  /** 0 still to 1 lively; absent means the default pace. */
  motion?: number;
  /** Rolled by the host at birth; the agent may replace it once with a look that fits the game. */
  placeholder?: true;
};
// ↑ src/shared/cover-recipe.ts

export type GameCover =
  | { kind: "procedural"; seed: number; style: CoverStyle; palette: number }
  | { kind: "image"; dataUrl: string }
  | LegacyShaderCover
  | CoverRecipe;
// ↑ src/shared/game-library.ts

export interface GameLibraryEntry {
  title?: string;
  pinned?: boolean;
  removed?: boolean;
  /** Folder trust is host metadata; project files cannot grant it. */
  trustProjectSettings?: boolean;
  cover?: GameCover;
  primaryThreadId?: string;
  /** The folder's content stamp as New game made it (`GameProject.scaffoldStamp`). */
  scaffoldStamp?: string;
  /** The title waits for the game's first idea; any title given since clears it. */
  provisional?: boolean;
}
// ↑ src/shared/game-library.ts

/**
 * What kind of game a folder holds, decided from the libraries and runtimes it actually loads —
 * never from the entry filename. `src/main.js` is Vite's stock layout as much as the studio's,
 * and reading it as "the template" is what served the user's own three.js game raw, with a bare
 * `three` import nothing could resolve.
 *
 * The kind says what the game *is*; `build` and `serve` say how it runs. A bundled Phaser game
 * is `phaser`, not `three-vite`.
 */
export type ProjectKind =
  | "studio-template"
  | "three-vite"
  | "three-modules"
  | "canvas2d"
  | "phaser"
  | "engine-export"
  | "own-script";
// ↑ src/shared/game-project.ts

/**
 * How a project runs. The studio's own template needs no build: `index.html` loads `src/main.js`
 * as a native ES module. A folder the user brings — Vite, TypeScript, any bundler — keeps its
 * own entry and build; the studio runs the build and serves its output instead of the sources
 * (served raw, `/src/main.ts` is refused by the browser and every critic judges a black frame).
 */
export interface ProjectShape {
  /** The page the preview serves, relative to the project — inside the build output when there is a build. */
  entry: string;
  /** The game's real entry module: what the main owner edits and other facets wire into. */
  main: string;
  /** Shell command that produces `entry` from the sources; null when the game runs as written. */
  build: string | null;
  /**
   * What "Install packages" runs — the manager the folder's own lockfile names, because
   * `npm install` in a pnpm project writes a second, divergent node_modules. Null when the
   * folder declares no dependencies at all.
   */
  install: string | null;
  /**
   * The folder brought its own game. Explicit, because no filename can carry it: a game may keep
   * the template's entry name and still be entirely its own, and the studio must never write its
   * scaffold beside a real one.
   */
  own: boolean;
  /** What the folder is, from its own evidence. */
  kind: ProjectKind;
  /** The folder the served page lives in, relative to the project; "." when it is served as written. */
  serve: string;
  /**
   * How long this game asks the studio to wait for it to boot, in milliseconds — clamped to a
   * minute, so a rewritten studio.json can cost at most that much patience. The user's knob (or
   * a worker's): the studio reads it and never writes it. Absent when the folder declares none,
   * and then the studio waits its own default.
   */
  bootMs?: number;
}
// ↑ src/shared/game-project.ts

/** A game linked to an Unreal project: its `.uproject` (absolute, real path) and when Genex linked it. */
export type EngineBinding = { kind: 'unreal'; project: string; linkedAt: string; };
// ↑ src/shared/game-engine.ts

export type FactSource = 'core' | 'link';
// ↑ src/shared/project-facts.ts

/** Where a fact came from: the core table, an engine link, or the `detect` of the plugin named. */
export type ProjectFactSource = FactSource | `plugin:${string}`;
// ↑ src/shared/project-facts.ts

/**
 * One thing a folder holds. `path` is POSIX and relative to the game, `"."` for its root; a link's
 * fact may be absolute when its project lies outside the folder.
 */
export interface ProjectFact {
  id: string;
  path: string;
  source: ProjectFactSource;
}
// ↑ src/shared/project-facts.ts

export type FolderHolds = 'nothing' | 'notes' | 'own-files' | 'unreadable';
// ↑ src/shared/project-facts.ts

export interface GameProject {
  primaryThreadId?: string;
  pinned?: boolean;
  cover?: GameLibraryEntry["cover"];
  lastOpenedAt?: string;
  name: string;
  dir: string;
  title: string;
  createdAt: string;
  /** `~/AI Games/pong` or `~/coding/my-game` — what the UI shows. */
  pathLabel: string;
  /** False when this folder is not a child of the default library. */
  library: boolean;
  /** How the game runs — the studio's own no-build shape, or a project with its own build. */
  shape: ProjectShape;
  /** `shape.own`: the folder brought its own game, so the studio builds it and serves its output. */
  built: boolean;
  /** The engine project Genex linked this game to; absent for a web game (`shared/game-engine.ts`). */
  engine?: EngineBinding;
  /**
   * What the folder holds, by `shared/project-facts.ts`: the core table, the enabled plugins'
   * `detect` and the engine link. Empty while the first message has not picked a kind.
   */
  facts: ProjectFact[];
  /**
   * What the folder holds while it has no facts (`FolderHolds`): nothing or notes (no kind yet), files
   * of its own of a kind no rule knows, or unreadable. Absent once it has facts, and from older lists.
   */
  holds?: FolderHolds;
  /** The moments the plugins that are on hook for this folder (`shared/plugin-hooks.ts`); absent: none. */
  hookEvents?: HookEvent[];
  /** What a port replaced, kept in the folder as the reference and no longer a kind of this game. */
  portedFrom?: ProjectFact[];
  /**
   * Whether `facts` hold `web-game` at the root; kept for parts that read it. Absent from a
   * descriptor made before it was recorded, read as a web game.
   */
  web?: boolean;
  /**
   * The folder's content stamp (`game.contentStamp`'s `all`) as New game made it from the template;
   * absent for a folder the studio did not make that way. While the folder's stamp still equals
   * it, nothing has been built in the game yet.
   */
  scaffoldStamp?: string;
  /** Named before anyone said what the game is: its first idea renames it in place (`nameFromIdea`). */
  provisional?: boolean;
}
// ↑ src/shared/game-project.ts

/**
 * A game folder's content stamps from one walk (`game.contentStamp` with `split`): everything,
 * and the game's sources without docs/ and Markdown. Null is unknown: the preview check runs.
 */
export interface ContentStamps {
  all: string | null;
  source: string | null;
}
// ↑ src/shared/game-project.ts

export interface ProjectRecent {
  name: string;
  title: string;
  pathLabel: string;
  dir: string;
  openedAt: string;
}
// ↑ src/shared/game-project.ts

export type ProjectStarter = 'web';
// ↑ src/shared/project-facts.ts

export type PluginCallBlocker = 'lock' | 'plan_mode';
// ↑ src/shared/plugins.ts

/**
 * What a start of the web starter answers instead of writing it while its chat is in Plan mode: the
 * chat's own `start_web_game` (as JSON) and the harness's `game.start` for a local model's.
 */
export interface StartHeldInPlan {
  blocker: PluginCallBlocker;
  message: string;
}
// ↑ src/shared/project-tools.ts

export type ContractWord = 'loaded' | 'attached' | 'missing';
// ↑ src/shared/game-project.ts

/**
 * What the studio's instrumentation actually got hold of on a page it just served (M4.2b).
 *
 * `game.validate` answers the same question from the folder's sources — a static judgement
 * about a page nobody loaded. This is the live one: the page is served, waited for and asked
 * what the hook attached to. `installed` is a game that calls `installStudio` itself,
 * `attached` is a game the hook found by watching it render, `none` is neither.
 */
export interface AttachReport {
  ok: boolean;
  contract: "installed" | "attached" | "none";
  /**
   * Did the studio's own page layer load at all? Every number below is read through it, so a
   * `false` here says the report is empty because the instrumentation never arrived — not
   * because the game is unconnected.
   */
  shim: boolean;
  reach: string | null;
  renderer: string | null;
  scene: string | null;
  camera: string | null;
  cameras: string[];
  eyes: string[];
  player: boolean;
  renders: number;
  frames: number;
  three: string[];
  reason: string | null;
  loadError: string | null;
  consoleErrors: number | null;
}
// ↑ src/shared/game-project.ts

/** What `game.export` wrote: the public roots it assembled, and what it left out. */
export interface ExportResult {
  dir: string;
  files: number;
  included: string[];
  excluded: string[];
}
// ↑ src/shared/game-project.ts

/** A still of the named title the critic compares against. */
export interface ReferenceFrame {
  label: string;
  mimeType: string;
  /** Raw bytes as base64. */
  data: string;
}
// ↑ src/shared/protocol.ts

/** `preview.profile`: begin a sampling session on a stage preview, then read, start or end it. */
export interface ProfileBegin {
  action: "begin";
  runId: string;
  stageId: string;
  scenarioId: string;
  handle: string;
  expectedRevision: Revision;
  warmupMs: number;
  sampleMs: number;
  counters?: boolean;
}
// ↑ src/shared/optimization.ts

export type ProfileRequest = ProfileBegin | { action: "read" | "end" | "start"; sessionId: string };
// ↑ src/shared/optimization.ts

export type CaptureSurface = 'canvas' | 'page' | 'auto';
// ↑ src/shared/preview-contract.ts

export interface PixelStats {
  width: number;
  height: number;
  sampled: number;
  /** 0–255, Rec.709. */
  meanLuma: number;
  litFraction: number;
  /** Fraction of sampled pixels per luma bin, low to high; sums to 1. Absent on degraded captures. */
  histogram?: number[];
  /** Mean luma (0–255) of horizontal thirds (top/middle/bottom) and vertical thirds (left/center/right). */
  bands?: { top: number; middle: number; bottom: number; left: number; center: number; right: number };
  /** Mean HSV saturation, 0–1. */
  saturation?: number;
  /** Luma standard deviation, 0–255. */
  contrast?: number;
  /**
   * Mean absolute luma step between horizontally adjacent pixels, 0–255. A smooth gradient
   * sits near 0; fine repeating texture that reads as moiré (a striped ceiling, a noise
   * tiling) pushes it up. The number behind a `moire` pixel check.
   */
  edgeDensity?: number;
  /**
   * 12-bin hue histogram (30° per bin, red first), each pixel weighted by its HSV saturation
   * and the whole normalised to sum 1 — a grey frame contributes nothing. The circular half
   * of the style distance.
   */
  hueHistogram?: number[];
  /** CIE Lab mean and standard deviation over the sample, [L, a, b]. */
  lab?: { mean: [number, number, number]; std: [number, number, number] };
  /** Up to 6 Lab centroids from a seeded, deterministic k-means, heaviest first; weights sum to 1. */
  palette?: Array<{ lab: [number, number, number]; weight: number }>;
  /** Mean luma (0–255) per horizontal sixteenth, top first — the frame's vertical structure. */
  lumaProfile?: number[];
}
// ↑ src/shared/preview-contract.ts

/** What a capture proved about the frame, plus whether the page even has a canvas to light. */
export interface PreviewPixelStats extends PixelStats {
  canvas: boolean;
  /**
   * Which path took the picture: `page` is the page's own end-of-frame read (M4.9a), which
   * works on a covered window; `compositor` is Electron's `capturePage`, which is what a
   * `surface: "page"` request asks for and what a failed page read falls back to. This says
   * HOW the frame was read, never WHICH surface was asked for — see `screenshotWithStats`.
   */
  source?: "page" | "compositor";
  /** Whether the frame was composited over the resolved page background before it was encoded. */
  composited?: boolean;
  /** Draw calls the page counted for the photographed frame, when the counters were live. */
  drawCalls?: number | null;
  /** Why the page-side read declined, when it did. */
  captureReason?: string | null;
  /** The context the photographed canvas hands out. */
  kind?: "webgl" | "webgl2" | "webgpu" | "2d" | null;
  /**
   * Who took this picture (M4.9a). `shim` is the studio's own end-of-frame read off the canvas;
   * `game` is a picture the build's own `capture()` answered with — the facade delegates
   * `capture()` and `captureInfo()` to the game, so a `game` frame and the draw count beside it
   * are the build's claim about itself, and a check that counts draws must not read them as the
   * canvas's own answer.
   */
  provenance?: "shim" | "game" | null;
  /** Which rungs the page-side capture climbed to get this frame (`frame`, `pump`, `async`, `game`). */
  ladder?: string[] | null;
}
// ↑ src/shared/preview-contract.ts

/** A crop rectangle as fractions of the frame: [x0, y0, x1, y1], origin top-left. */
export type CropRect = [number, number, number, number];
// ↑ src/shared/preview-contract.ts

export interface PixelDiff {
  /** Fraction of compared pixels whose luma moved by more than DIFF_THRESHOLD. */
  diffFraction: number;
  /** Mean absolute luma difference, 0–255. */
  meanAbsDiff: number;
  /** diffFraction per cell of a 3×3 grid, row-major (top-left first). */
  grid: number[];
  /** Compared pixel count; 0 when the frames could not be compared (size mismatch, empty). */
  compared: number;
}
// ↑ src/shared/preview-contract.ts

export interface PreviewConsoleEntry {
  at: number;
  level: string;
  message: string;
  source?: string;
  line?: number;
}
// ↑ src/shared/preview-contract.ts

export type PreviewGone = 'killed' | 'oom' | 'crashed' | 'launch-failed' | 'abnormal-exit' | 'integrity-failure';
// ↑ src/shared/preview-contract.ts

/** What `PreviewPort.status()` and the `preview.status` RPC answer. */
export interface PreviewPortStatus {
  project: string | null;
  url: string | null;
  crashed: boolean;
  /**
   * Why the renderer went away while `crashed`; null while it runs. Absent from a port that does
   * not say (a fake, an older port), which reads as no reason given.
   */
  gone?: PreviewGone | null;
  /**
   * The view's size now, in pixels: the space of its captures. A window put at another size by
   * `preview.viewport` reads that size until its lease is released or a computer session takes it
   * (which puts it back at the facet size). Absent from a port that cannot say.
   */
  viewSize?: { width: number; height: number };
  unresponsive: boolean;
  loadError: string | null;
  consoleErrors: number | null;
  consoleAvailable?: boolean;
}
// ↑ src/shared/preview-contract.ts

export type ReadyVia = 'shim' | 'contract' | 'none';
// ↑ src/shared/preview-contract.ts

export type ReadyPhase = 'ready' | 'boot' | 'failed' | 'unknown';
// ↑ src/shared/preview-contract.ts

/** What the studio waited for, and what it got. `preview.ready` answers with exactly this. */
export interface ReadyResult {
  ready: boolean;
  /** The STUDIO's wait — not the page's boot, which is `pageMs`. */
  ms: number;
  pageMs: number | null;
  /** The wait ended with no ready page and a budget spent — the studio's, or the page's own. */
  timedOut: boolean;
  /** The page said its own boot budget was spent, whatever the studio's clock did. */
  pageTimedOut: boolean;
  budgetMs: number;
  via: ReadyVia;
  phase: ReadyPhase;
  reason: string | null;
  polls: number;
  gesture: { needed: boolean; done: boolean; reasons: string[] };
}
// ↑ src/shared/preview-contract.ts

export interface BuildObservation {
  ok: boolean;
  reasons: string[];
  pixels: PreviewPixelStats | null;
  studioMissing: boolean;
  frameBefore: number | null;
  frameAfter: number | null;
  frameAdvanced: boolean;
  running: boolean | null;
  fps: number | null;
}
// ↑ src/shared/preview-contract.ts

/**
 * An agent's screen — the hidden preview window one worker is driving with the computer
 * tool, as the studio window shows it: the last frame, where the cursor is, what the agent
 * just did. Main emits `preview.screen` (opened/closed) and `preview.frame` (a new picture);
 * the Builds graph shows each on the node of the part it works on, the lead's on the lead's.
 */
export type AgentScreenRole = "builder" | "playtester" | "scout" | "judge" | "director";
// ↑ src/shared/agent-screen.ts

export interface AgentScreen {
  /** The preview-pool handle — the card's identity for the life of the session. */
  handle: string;
  /** Who is at the keyboard: the facet's title or id, "playtester", "scout", "director". */
  label: string;
  project: string;
  runId: string | null;
  facetId: string | null;
  role: AgentScreenRole;
}
// ↑ src/shared/agent-screen.ts

export type ScreenDeed = 'load' | 'look' | 'click' | 'press' | 'type' | 'drag' | 'move' | 'scroll' | 'wait' | 'reload';
// ↑ src/shared/agent-screen.ts

/** One action at a screen: what it was, and for a press the keys as the agent named them ("space", "ArrowRight"). */
export interface ScreenAct {
  deed: ScreenDeed;
  keys?: string[];
}
// ↑ src/shared/agent-screen.ts

export interface AgentScreenFrame extends AgentScreen {
  /** A JPEG of the window, downscaled for the card, base64. */
  jpeg: string;
  /** The window's size — the coordinate space of `cursor`. */
  width: number;
  height: number;
  cursor: { x: number; y: number };
  /** What the agent just did ("left click at 412,300", "key i", "capture default"). */
  caption: string | null;
  /** The same action as a code; absent from a producer that predates it. */
  act?: ScreenAct;
  at: number;
}
// ↑ src/shared/agent-screen.ts

export type JobRole = 'lead' | 'chat' | 'worker';
// ↑ src/shared/jobs.ts

export type JobState = 'failed' | 'running' | 'succeeded' | 'stopped' | 'timed_out' | 'interrupted';
// ↑ src/shared/jobs.ts

export type JobStopper = 'agent' | 'person' | 'scope_ended' | 'quit';
// ↑ src/shared/jobs.ts

/**
 * One job as the harness reads it (`jobs.list`): what it is, who started it and how it ended,
 * never where its folder, log or process is. `endSeq` orders the ends of one game's jobs.
 */
export interface JobView {
  id: string;
  title: string;
  role: JobRole;
  /** The title of the worker that started it, when one did. */
  worker?: string;
  command: string;
  state: JobState;
  exitCode: number | null;
  endedAt: string | null;
  endSeq: number | null;
  /** How long it ran, once it ended. */
  durationMs: number | null;
  stoppedBy: JobStopper | null;
}
// ↑ src/shared/jobs.ts

/**
 * Every method the host serves the harness: `params` is what `ctx.call` sends, `result` what the
 * call resolves to. A method that takes nothing has `void` params.
 */
export interface HarnessHostApi {
  // — assets —
  "assets.inventory": { params: { project: string }; result: ProjectAssets };
  "assets.checkpoint": {
    params: { project: string; runId: string; assetIds?: string[] };
    result: { revision: string; files: string[] };
  };

  // — event log —
  "events.append": { params: { threadId?: string; batch: EventData[] }; result: string };
  "events.list": { params: { threadId?: string; after?: string; limit?: number }; result: EventEnvelope[] };
  "events.head": { params: { threadId?: string }; result: string | null };
  "events.messages": { params: { threadId?: string }; result: Message[] };
  /**
   * The follow-up queue records of every conversation that still owes an answer (a message not
   * yet answered or removed) or holds its queue: what a boot restores its inbox from, instead of
   * reading every conversation's whole log. The records read exactly as the whole log would.
   */
  "events.inbox": { params: void; result: Array<{ threadId: string; events: EventEnvelope[] }> };
  "thread.main": { params: void; result: string };
  "thread.create": { params: { title?: string }; result: string };
  "thread.list": { params: void; result: ConversationRecord[] };
  "thread.fork": { params: { threadId: string; upToInclusive: string; title?: string }; result: string };
  "artifact.read": { params: { threadId?: string; artifactId: string }; result: unknown };
  "artifact.write": { params: { threadId?: string; artifactId: string; value: unknown }; result: number };

  // — turns —
  "turn.begin": {
    params: { threadId?: string; input?: Message[]; metadata?: Record<string, unknown> };
    result: { turnId: string; sessionId: string; head: string };
  };
  "turn.append": { params: { turnId: string; batch: EventData[] }; result: string };
  /** End a turn; `outcome` is how the loop ended it (a TurnStop code), kept on its `turn_ended`. */
  "turn.end": {
    params: { turnId: string; status?: "ok" | "error" | "cancelled"; outcome?: string };
    result: string | null;
  };

  // — optimization: registered, isolated source authority —
  "optimization.baseline": {
    params: { project: string; snapshotId: string };
    result: { snapshotId: string; commit: string; tree: string };
  };
  "optimization.open": {
    params: { project: string; runId: string; baselineSnapshotId: string };
    result: OptimizationCandidate;
  };
  "optimization.freeze": {
    params: { candidateId: string };
    result: { diff: string; changedFiles: string[]; revision: Revision };
  };
  "optimization.promote": {
    params: { candidateId: string; expectedLive: Revision; verifiedCandidate: Revision; resultArtifact: string };
    result: { outcome: string; revision: Revision; reason: string | null };
  };
  "optimization.reconcile": {
    params: { project: string; baseline: Revision; candidate: Revision | null };
    result: { revision: Revision; retained: string };
  };
  "optimization.close": { params: { candidateId: string }; result: { closed: boolean } };

  // — snapshots —
  "snapshot.create": {
    params: { scope?: HarnessSnapshotScope; reason: string; project?: string; healthy?: boolean };
    result: SnapshotRecord;
  };
  "snapshot.restore": {
    params: {
      snapshotId: string;
      project?: string;
      reason?: string;
      /** Narrows the restore below what the record captured, e.g. game-only from a "both" snapshot. */
      scope?: HarnessSnapshotScope;
      /** The chat and run the restore answers to: while that chat plans, the game's restore steps wait. */
      threadId?: string;
      runId?: string;
    };
    result: boolean;
  };
  "snapshot.list": { params: void; result: SnapshotRecord[] };
  "snapshot.markHealthy": { params: { snapshotId: string }; result: boolean };
  "snapshot.diff": { params: { workspace?: string; from: string; to?: string }; result: string };
  /** A detached, playable, sandbox-writable fork of a game under scratch, at `commit` or the live HEAD. */
  "snapshot.worktree": {
    params: { project: string; commit?: string; name: string; runId?: string };
    result: { path: string; commit: string };
  };
  "snapshot.removeWorktree": { params: { project: string; path: string }; result: boolean };

  // — plugins and connectors —
  "plugins.preflightMultiplayer": {
    params: { project: string; threadId?: string };
    result: { ready: boolean; reason: string; hostedVerified: false };
  };
  /**
   * The plugin tools and guidance for the game `project` names, by its facts (none named, or a
   * game with no kind yet: a web game's), and the tools on offer that make a kind of project.
   */
  "plugins.tools": {
    params: { project?: string | null };
    result: { tools: PluginTool[]; guidance: string; revision: number; kinds: PluginKindOffer[] };
  };
  /**
   * The kinds of worker the plugins on offer declare for the game `project` names, by its facts
   * (`PluginManifest.workerTypes`), each with its tools as agent names: what a lead may start.
   */
  "plugins.workerTypes": { params: { project: string }; result: WorkerType[] };
  /**
   * The agent's search for a Genex plugin, by a fact or words: installed plugins (on, then off) and
   * Genex's catalog, never another source; read-only.
   */
  "plugins.find": {
    params: { project?: string | null; fact?: string | null; text?: string | null };
    result: PluginsFindAnswer;
  };
  /**
   * The turn-it-on card in `threadId`, a chat of `project`, for a plugin that is installed but off
   * or in Genex's catalog; it turns nothing on. Refused (`shown: false`, nothing written) otherwise.
   */
  "plugins.suggest": {
    params: { project: string; threadId: string; plugin: string; reason?: string };
    result: PluginsSuggestAnswer;
  };
  /** What this game's builders can use, for a conversation that cannot call it (the local coordinator). */
  "capabilities.describe": { params: { threadId: string; project?: string }; result: string };
  "plugins.invoke": {
    params: {
      project: string;
      threadId?: string;
      name: string;
      args: Record<string, unknown>;
      /** The harness's own step: a tool the plugin keeps for the harness. An agent's call never sets it. */
      step?: boolean;
      /** The step writes (a chat's checkpoint, a run's save point or editor change), which Plan mode holds back. */
      checkpoint?: boolean;
    };
    result: unknown;
  };
  "mcp.tools": {
    params: { project?: string | null };
    result: { tools: McpLiveTool[]; guidance: string; revision: number };
  };
  "mcp.invoke": {
    params: { project: string; threadId?: string; name: string; args?: Record<string, unknown> };
    result: LiveToolResult;
  };
  /**
   * A worker writing in place starts: it takes Genex's one writer in place in the game folder,
   * across every pool of the game, and the per-game locks of the plugins that are on that the
   * game's tools need, until `locks.release`. `labels` names the apps those locks guard. Never
   * waits: a lock another worker holds answers `busy`, in words naming who, and nothing is taken.
   * A worker is known by the run that started it, else its chat, and its id.
   */
  "locks.hold": {
    params: { project: string; threadId: string; runId?: string | null; holder: { id: string; title: string } };
    result: { held: true; labels: string[] } | { busy: string };
  };
  /**
   * A checkpoint of the game folder: the enabled plugins' `checkpoint.before` steps, a snapshot
   * named for `label`, then their `checkpoint.after` steps, under their locks. `onlyIfUnsaved`
   * skips it when the locks' probes say nothing is unsaved, or one can't tell. Held while the chat
   * plans.
   */
  "checkpoint.take": {
    params: {
      project: string;
      threadId?: string | null;
      runId?: string | null;
      label: string;
      onlyIfUnsaved?: boolean;
    };
    result: CheckpointAnswer;
  };
  /**
   * One of Genex's moments the harness announces (`SEED_FIRED_HOOK_EVENTS`): the enabled plugins'
   * steps for it run in order and their answers come back. A restore announced here is a restart:
   * no file changes.
   */
  "hooks.fire": {
    params: {
      project: string;
      threadId?: string | null;
      runId?: string | null;
      on: HookEvent;
      turn?: string | null;
      label?: string | null;
      worker?: { id: string; title: string; type?: string | null } | null;
    };
    result: HookReport;
  };
  /** A worker writing in place ended: every lock it holds in the game is let go; another's are untouched. */
  "locks.release": {
    params: { project: string; threadId: string; runId?: string | null; holder: { id: string } };
    result: boolean;
  };

  // — sandboxed execution —
  "run.exec": {
    params: { command: string; cwd?: string; project?: string; timeoutMs?: number; label?: string };
    result: ExecResult;
  };

  // — engines —
  "engine.describe": { params: void; result: EngineDescriptor[] };
  "studio.context": {
    params: void;
    result: {
      settings: StudioSettingsView;
      games: Array<{ name: string; title: string }>;
      recentActivity: StudioActivityItem[];
      pendingProposals: Array<{ skill: string; title?: string; summary?: string[]; rationale: string | undefined }>;
    };
  };
  "context.policy": { params: { engine: string; model?: string; threadId?: string }; result: ContextSettings };
  /** The Self-improvement switch, asked by the harness before each thing it would learn. */
  "learning.enabled": { params: void; result: boolean };
  "engine.complete": { params: HarnessCompleteParams; result: CompleteResponse };
  /**
   * Stop: aborts a thread's completions, a project's delegations, or the delegation in one worktree
   * (with `worker`, the in-place worker of that id working in `cwd`).
   */
  "engine.abort": {
    params: { threadId?: string; cwd?: string; project?: string; worker?: string };
    result: { aborted: number };
  };
  /**
   * Steering that cannot wait (M3.4): cuts one worktree's build turn short so its caller can resume
   * it (with `worker`, the in-place worker of that id working in `cwd`).
   */
  "engine.interrupt": { params: { cwd: string; worker?: string }; result: { interrupted: boolean } };
  "engine.delegate": { params: HarnessDelegateParams; result: DelegateResult };
  /**
   * Steer: messages the person sent while the chat's turn works, into the session answering that
   * turn (`chatTurn` is `into`). `accepted` lists what the session took; `how` is how (`SteerDelivery`
   * in `shared/message-queue.ts`), null when it took nothing. `interrupt: false` takes them only
   * into a session that reads them mid-turn, and never cuts one short.
   */
  "engine.steer": {
    params: { threadId: string; into: string; messages: SteerMessage[]; interrupt?: boolean };
    result: { how: SteerDelivery | null; accepted: string[] };
  };
  "coordinator.tool": {
    params: { threadId: string; runId: string; messageId?: string; name: string; args?: Record<string, unknown> };
    result: string;
  };
  "engine.delegations": {
    params: void;
    result: Array<{ project: string; cwd: string; engine: string; startedAt: number }>;
  };
  "engine.hardware": { params: void; result: HardwareReport };

  // — games —
  "game.list": { params: void; result: GameProject[] };
  "game.setCover": { params: { project: string; threadId?: string } & Record<string, unknown>; result: string };
  /** Harnesses installed before recipes still author custom GLSL covers through this. */
  "game.setCoverShader": { params: { project: string; surface: string; threadId?: string }; result: LiveToolResult };
  /**
   * The folder's content stamp; `split` answers both stamps from one walk ({@link ContentStamps}).
   * A caller that does not ask gets the full stamp as a string, as before.
   */
  "game.contentStamp": { params: { project: string; split?: boolean }; result: string | ContentStamps | null };
  "game.recents": { params: void; result: ProjectRecent[] };
  /**
   * Make a game's folder: Genex's bookkeeping only, or with the starter `kind` names (`"web"`, or
   * an older caller's `"studio-template"`); any other kind is refused.
   */
  "game.scaffold": { params: { name: string; title?: string; threadId?: string; kind?: string }; result: GameProject };
  /**
   * Write a starter into a game that has no kind yet (no facts); a game with a kind is refused.
   * `threadId`, the chat a local model's `start_web_game` answers: while that chat (this game's) is
   * in Plan mode nothing is written and the Plan answer comes back instead. A call with no thread (a
   * Loop's start, which runs only once its run is approved) is not checked.
   */
  "game.start": {
    params: { project: string; starter: ProjectStarter; threadId?: string };
    result: GameProject | StartHeldInPlan;
  };
  "game.validate": {
    params: { project: string; candidateId?: string };
    result: { ok: boolean; problems: string[]; warnings: string[]; contract: ContractWord };
  };
  /** The live half of `game.validate`: serve the page, wait for it, ask what the hook got hold of. */
  "game.attached": {
    params: { project: string; root?: string; entry?: string; candidateId?: string };
    result: AttachReport;
  };
  /**
   * v2 contract upgrade: an older `src/studio.js` that is a copy the studio shipped gets the template's
   * copy, the old one kept beside it. An older copy anyone edited is left alone and answered with
   * `edited` and the `generation` it stays at; its `src/hud.js` stays with it.
   * `hud` is there when the game's `src/hud.js` was older than the template's: replaced (a shipped copy,
   * kept as `backup`) or left alone (an edited copy, or one beside a kept contract, still at `generation`).
   */
  "game.upgradeContract": {
    params: { project: string };
    result: {
      upgraded: boolean;
      reason?: string;
      materialsAdded?: boolean;
      backup?: string | null;
      edited?: boolean;
      generation?: number;
      hud?: { generation: number; replaced: boolean; backup?: string };
    };
  };
  "game.read": { params: { project: string; file: string; candidateId?: string }; result: string | GameImageRead };
  "game.write": {
    params: { project: string; file: string; contents: string; candidateId?: string };
    result: { bytes: number };
  };
  "game.tree": { params: { project: string; candidateId?: string }; result: string[] };
  "game.export": { params: { project: string; target?: string }; result: ExportResult };
  /** The stills in `<project>/references/`, sniffed and resized. */
  "game.references": {
    params: { project: string; max?: number; maxPx?: number };
    result: { frames: ReferenceFrame[]; skipped: Array<{ file: string; why: string }> };
  };

  // — preview (the senses): an omitted `handle` is the studio's stand-in for the live view (the
  // live view itself in a build with no hidden windows); only the person changes their Live —
  "preview.load": {
    params: {
      project: string;
      entry?: string;
      root?: string | null;
      handle?: string;
      candidateId?: string;
      revision?: Revision;
    };
    result: string;
  };
  "preview.profile": { params: ProfileRequest & { handle: string }; result: unknown };
  "preview.reload": { params: { handle?: string; retry?: boolean }; result: boolean };
  "preview.screenshot": {
    params: {
      quality?: number;
      runId?: string;
      label?: string;
      handle?: string;
      page?: boolean;
      surface?: CaptureSurface;
    };
    result: {
      base64: string;
      bytes: number;
      path: string | null;
      stats: PreviewPixelStats | null;
      surface: CaptureSurface | null;
    };
  };
  /** What the page holds outside the canvas: a DOM menu, an HTML HUD, a loader. */
  "preview.pageUi": { params: { handle?: string }; result: unknown };
  /**
   * `__studio.state()`, bounded by structure: over the studio's budget its largest lists become
   * `{__elided, length, chars}` stubs and the root names them under `__cut`. `keep` names the
   * dotted paths a board reads (at most 64, each up to 120 characters); they are cut last.
   */
  "preview.state": { params: { handle?: string; keep?: string[] }; result: unknown };
  "preview.call": { params: { method: string; arg?: unknown; handle?: string }; result: unknown };
  /** Read-only JS over the game's own graph; the answer is untrusted JSON, size-capped by the port. */
  "preview.evaluate": { params: { expression: string; handle?: string }; result: unknown };
  /** A `vision` check's crop, cut from a saved judged frame — never re-captured. */
  "preview.crop": {
    params: { runId: string; path: string; crop: CropRect; label?: string; handle?: string; quality?: number };
    result: { path: string; base64: string; bytes: number; width: number; height: number } | null;
  };
  /** Challenger against incumbent on one camera: diff fraction and heatmap. */
  "preview.diff": {
    params: { runId: string; a: string; b: string; label?: string; handle?: string };
    result: (PixelDiff & { heatmapPath: string | null }) | null;
  };
  "preview.input": {
    params: { actions?: PreviewInputAction[]; handle?: string };
    result: { ok: boolean; applied: number; width: number; height: number };
  };
  "preview.console": { params: { sinceMs?: number; handle?: string }; result: PreviewConsoleEntry[] };
  "preview.gpuErrors": { params: { handle?: string }; result: string[] };
  "preview.status": { params: { handle?: string }; result: PreviewPortStatus };
  /** Readiness is a fact the page reports, not a sleep. */
  "preview.ready": { params: { handle?: string; timeoutMs?: number; gesture?: boolean }; result: ReadyResult };
  /** A knock: the trusted click that grants user activation. */
  "preview.gesture": {
    params: { handle?: string; x?: number; y?: number; keys?: string[] };
    result: { knocked: boolean; trusted: boolean | null };
  };
  /** What the user's own window is showing right now: their game folder, or a build they chose to play. */
  "preview.showing": {
    params: void;
    result: { project: string; root: string | null; entry: string | undefined; loaded: string | null } | null;
  };
  "preview.observe": { params: { handle?: string }; result: BuildObservation };
  "preview.acquire": { params: { label?: string; purpose?: "optimization" }; result: { handle: string } };
  "preview.release": { params: { handle: string }; result: boolean };
  /**
   * One leased window at another size (the art director's 1600×900 look), for that lease only:
   * clamped to 320–1920 × 240–1200 and back at the facet size when the lease is released. Never
   * Live, the stand-in or a window a computer session plays in, so its view never changes size:
   * handing the lease to a session puts it back at the facet size, and the caller sizes it again
   * afterwards (`preview.status` `viewSize` says the size it is at now).
   */
  "preview.viewport": {
    params: { handle: string; width: number; height: number };
    result: { handle: string; width: number; height: number };
  };
  /** Pixel stats of an encoded still — the same numbers a capture yields. */
  "preview.statsOf": {
    params: { base64?: string; path?: string; handle?: string };
    result: { stats: PixelStats; width: number; height: number } | null;
  };
  /** LEFT | RIGHT composite of a reference still and a build frame. */
  "preview.pair": {
    params: { runId: string; left: StillSource; right: StillSource; label?: string; height?: number; handle?: string };
    result: { path: string; base64: string; bytes: number } | null;
  };
  "preview.screens": { params: void; result: AgentScreenFrame[] };
  "preview.capacity": {
    params: void;
    result: {
      max: number;
      inUse: number;
      free: number;
      live: boolean;
      headless: boolean;
      memory: { freeMb: number; totalMb: number };
    };
  };

  // — jobs: the long processes the agents start, which the app owns —
  /**
   * A game's jobs, read-only: only those that ended after `endedAfter` (an end number) when it is
   * given, only `runId`'s (its lead's and its workers') when that is, and the game's last end
   * number, read together so a reader that goes on from `seq` misses none and hears none twice.
   * The harness can neither start nor stop a job.
   */
  "jobs.list": {
    params: { project: string; runId?: string | null; endedAfter?: number | null };
    result: { jobs: JobView[]; seq: number };
  };

  // — runs, guardian, ui —
  "run.artifact": { params: { runId: string; name: string; base64: string }; result: string };
  "guardian.rebuild_and_restart": { params: { reason: string }; result: { updateId: string; snapshotId: string } };
  /**
   * Try a change to the harness's own files in a validation fork before writing it: the fork is
   * type-checked (for code) and booted. Nothing live is touched; a pass lets the snapshot the
   * harness takes after writing the same code become healthy at once.
   */
  "guardian.validate_edit": { params: { files: Array<{ file: string; contents: string }> }; result: SelfEditVerdict };
  /**
   * The one way the harness changes one of its own files (`write_own_file`, `write_skill`,
   * `install_tool`): the host tries the change in a validation fork, snapshots before and after,
   * writes it, and records it where Activity and Undo read it. Prompts and skills are
   * write-denied to every agent process, so nothing else changes them. `title` and `summary` are
   * the plain words Activity shows for the change; the host bounds them.
   */
  "guardian.write_self": {
    params: { file: string; contents: string; reason: string; title?: string; summary?: string[] };
    result: SelfWriteResult;
  };
  /** A harness notification forwarded to the renderer as a `UiEvent`, name and payload as sent. */
  "ui.notify": { params: { type: string; payload?: unknown }; result: boolean };
}
// ↑ src/shared/harness-api.ts

export type HarnessHostMethod = keyof HarnessHostApi;
// ↑ src/shared/harness-api.ts

export type HarnessParams<K extends HarnessHostMethod> = HarnessHostApi[K]["params"];
// ↑ src/shared/harness-api.ts

export type HarnessResult<K extends HarnessHostMethod> = HarnessHostApi[K]["result"];
// ↑ src/shared/harness-api.ts

export type HostRefusal = 'UnknownMethod' | 'InvalidParams';
// ↑ src/shared/harness-api.ts

/** Composer Loop on a chat turn — hours from the stepper, stills the user dropped. */
export interface LoopCommission {
  hours: number;
  frames?: ReferenceFrame[];
}
// ↑ src/shared/protocol.ts

/** Who plans, builds and judges — one model id per job; `undefined`/"default" is the engine's own default. */
export interface RunRoles {
  /** Explicit reasoning per role; absent means that role model's own default. */
  efforts?: Partial<Record<"planner" | "builder" | "judge", string>>;
  planner?: string;
  builder?: string;
  judge?: string;
  /**
   * The other subscription, for the workers and/or the judges (cross-provider roles): the model
   * in that slot is then one of that engine's. Never the orchestrator, which is the run's engine.
   */
  engines?: { builder?: string; judge?: string };
}
// ↑ src/shared/protocol.ts

export interface AutopilotCommission {
  hours?: number;
  frames?: ReferenceFrame[];
  /** The composer's roles panel: explicit orchestrator / workers / judges picks (harness-seed/loop/model-roles.ts). */
  roles?: RunRoles;
  /** Request host-owned explicit approval before execution (default off). */
  reviewPlan?: boolean;
}
// ↑ src/shared/protocol.ts

export type MessageOrigin = 'command-result';
// ↑ src/shared/protocol.ts

export interface RunReference {
  name: string;
  /** Saved file paths (the morning-review timeline). */
  shots: string[];
  notes?: string;
  /**
   * "reference" is a real game to beat (the blind panel is the exit); "direction" is free text
   * to push toward — no panel, the run spends its whole budget iterating.
   */
  kind?: "reference" | "direction";
  /** Pixels the critic actually sees. Not written into the event log. */
  frames?: ReferenceFrame[];
}
// ↑ src/shared/protocol.ts

export interface RunSpec {
  runId: string;
  goal: string;
  project: string;
  /** "autopilot" decomposes into facet loops; absent = the plain gauntlet. */
  mode?: "autopilot";
  /**
   * The programmed pipeline on purpose: planner → base → facet loops → merge. A
   * delegated engine's Autopilot is otherwise the director's — one session that decides the run.
   */
  classic?: boolean;
  /**
   * How a director's session is driven. "wake" (absent): the lead ends its turn after each
   * decision and the harness wakes the same session with a digest when something happens.
   * "turn": the long turn before the wake loop, with `wait` and continuation prompts — kept for
   * one release, set by rigs and dev dispatches; a run that names none follows
   * `DIRECTOR_LOOP_ENV` in the studio's environment.
   */
  directorLoop?: "wake" | "turn";
  /**
   * gauntlet reference bar — Named / Fetchable / Comparable. `kind` widens it:
   * "reference" is a real game to beat (the blind panel is the exit condition); "direction" is
   * free text to push toward — no reference panel. Completion is controlled by budgets.
   */
  reference: RunReference;
  /** observationDelays: backoff (ms) before re-trying a blind camera — a test/ops knob. */
  budgets: {
    wallClockMs: number;
    /** The composer's ∞: run until the judge is satisfied; `wallClockMs` is then only the safety ceiling. */
    untilSatisfied?: boolean;
    /** Explicit intent; absent records retain legacy untilSatisfied semantics. */
    completionPolicy?: "goal" | "duration";
    maxIterations?: number;
    observationDelays?: number[];
    /** v2 loop knobs: the pre-evidence code review (default on) and its model half (default on for delegated engines). */
    review?: boolean;
    modelReview?: boolean;
  };
  engine?: string;
  /** The builders' model. Arrives as the composer's pick; the harness resolves it at launch. */
  model?: string;
  /** The builders' engine, only when it is not the run's own (stamped from `roles.engines.builder`). */
  builderEngine?: string;
  judgeEngine?: string;
  judgeModel?: string;
  /**
   * Who plans, builds and judges — stamped by the harness at launch from the pick
   * (harness-seed/loop/model-roles.ts). `undefined` in a slot is the engine's own default.
   */
  roles?: RunRoles;
  /** Set once the harness has applied `roles` to `model`/`judgeModel` (a resume must not resolve twice). */
  rolesApplied?: boolean;
  /** The composer's "review the plan before building" tick; the harness writes it onto the run (loop/main.ts) and the director holds its first worker for the user's go. */
  reviewPlan?: boolean;
}
// ↑ src/shared/protocol.ts

export type BootReason = 'cold_start' | 'self_update' | 'watchdog_restore' | 'crash_restart';
// ↑ src/shared/protocol.ts

/** What the reborn agent is told about its own restart — read from the log, not from us. */
export interface BootNotice {
  reason: BootReason;
  updateId?: string;
  snapshotId?: string;
  detail?: string;
  /**
   * Runs the incarnation that just died was in the middle of. Nothing can judge or commit them
   * any more — the host aborted every contractor the moment the child exited — so the reborn
   * loop owes each one an ending in its own thread. Absent on a cold start: the app repairs the
   * log itself before the harness wakes (StudioCore#closeInterruptedWork).
   */
  openRuns?: string[];
}
// ↑ src/shared/protocol.ts

export type DispatchAction =
  | {
      type: "user_message";
      threadId: string;
      text: string;
      /** The queue records the message under this id (the composer's optimistic bubble). */
      messageId?: string;
      engine?: string;
      model?: string;
      effort?: string;
      preferences?: ModelPreferences;
      project?: string;
      newProject?: boolean;
      studioThread?: boolean;
      resume?: string;
      newRun?: boolean;
      /** Absolute folder this chat is pinned to — shown in the prompt so the model stops guessing. */
      projectDir?: string;
      /** Extra stills folders the user named; readable, not writable. */
      extraReads?: string[];
      /** Stills already loaded so the model sees pixels without hunting the disk. */
      stills?: ReferenceFrame[];
      /** How many of `stills` the composer attached (they come first); a rewind gives them back. */
      pickedImages?: number;
      /** Reference files this message saved in the game (relative paths); a rewind with files removes them. */
      references?: string[];
      /** Composer Loop: the chat may start an unattended build when the ask needs one. */
      loop?: LoopCommission;
      /** Composer Autopilot: the chat may launch a build that decomposes into facets and runs until satisfied. */
      autopilot?: AutopilotCommission;
      /** Words the chat wrote itself (a command's result); the queue keeps it and the transcript hides it. */
      origin?: MessageOrigin;
    }
  | { type: "compact"; threadId: string; engine?: string; model?: string }
  | { type: "cancel"; threadId?: string }
  | { type: "queue_message"; threadId: string; messageId: string; operation: "hold" | "edit" | "remove"; text?: string }
  | { type: "queue_resume"; threadId: string }
  /**
   * The chat was rewound (capability "rewind"). `frames`, when present, is the Loop mood board
   * the interview still has after it (null: none); absent, the board is untouched.
   */
  | { type: "rewind"; threadId: string; frames?: ReferenceFrame[] | null }
  | { type: "healthcheck" }
  /** Run the loop's deterministic self-test (the architect's bar); rejects with the first failure. */
  | { type: "selftest" }
  | { type: "run_start"; threadId: string; run: RunSpec; resume?: boolean }
  | { type: "run_stop"; runId: string }
  | { type: "autopilot_resume"; threadId: string; runId: string }
  /**
   * The director's tools: a live tool call from the run's director session, hosted
   * by the studio, forwarded to the harness that owns the workers, the judges and the merge.
   * Unlike every other dispatch this one answers with a value — the tool's result.
   */
  | { type: "director_tool"; runId: string; name: string; args: Record<string, unknown> }
  /**
   * A worker tool (`WorkerTool`) the chat's own session called during the chat turn `turn` (its
   * message id), forwarded to the harness's worker pool for that turn. Answers with the tool's result.
   */
  | { type: "worker_tool"; threadId: string; turn: string; name: string; args: Record<string, unknown> }
  | { type: "skillopt_start"; threadId: string; options?: Record<string, unknown> }
  | { type: "boot_notice"; notice: BootNotice };
// ↑ src/shared/protocol.ts
