/**
 * Home's Suggest prompt: one game idea at a time, put in the composer for someone who does not
 * know where to start. Each is one sentence a person might type, small enough to build in one run.
 */

/** The ideas Suggest prompt draws from. */
export const PROMPT_IDEAS = [
  "A cozy fishing game on a tiny island where you sell your catch at the dock",
  "A top-down racer with drifting and a boost that charges in corners",
  "A platformer where gravity flips every time you jump",
  "A snail racing game with power-ups and very slow drama",
  "A tower defense game played on the rim of a teacup",
  "A space shooter where every enemy you destroy becomes part of your ship",
  "A puzzle game about folding paper to connect two halves of a map",
  "A rhythm game where you water plants to the beat",
  "A roguelike dungeon crawler set inside a vending machine",
  "A city builder on the back of a giant walking turtle",
  "A stealth game where a cat steals socks from a sleeping house",
  "A farming sim on a floating island that drifts between seasons",
  "A mini golf course on the surface of the moon with low gravity",
  "A survival game on a raft that grows from things you fish out of the sea",
  "A pinball table where the ball is a tiny knight fighting monsters",
  "A cooking game in a food truck that serves ghosts at midnight",
  "A detective game where you question houseplants about a missing cookie",
  "A sky courier delivering letters between floating towns on a glider",
  "A match-three puzzle where matches grow a forest",
  "A dungeon where you play the monster defending its treasure from heroes",
  "A pixel-art fishing game under a frozen lake",
  "A tiny planet you walk around, planting trees until it turns green",
  "A boss rush where every boss is a different kitchen appliance",
  "A lighthouse keeper guiding ships through a storm by turning the beam",
  "A sokoban puzzle with ice tiles and a penguin who cannot stop sliding",
  "A neon arcade shooter where your bullets bounce off the walls",
  "A slow train journey where you trade goods between stations",
  "A wizard duel where spells are drawn with the mouse",
  "A beekeeping game where you plan a garden to keep the hive happy",
  "A treasure hunt on a sunken pirate ship with limited air",
  "A zen sand garden where you rake patterns around stones",
  "A lane-switching runner through a candy factory",
  "A chess variant where pieces level up after each capture",
  "A hot air balloon game where you ride the winds between islands",
  "A haunted house you redecorate to scare away noisy guests",
  "A breakout clone where the bricks fight back",
  "A rescue helicopter game in a flooded city",
  "A card battler where your deck is a stack of recipes",
  "A frog hopping across lily pads that sink when you stay too long",
  "A museum night guard game where the exhibits come alive",
  "A desert caravan trading spices across shifting dunes",
  "A one-button game about a whale jumping out of the ocean",
  "A paper airplane flying through an office without hitting coworkers",
  "A colony sim for ants building tunnels under a picnic",
  "A tiny submarine exploring a glowing deep-sea cave",
  "A rooftop parkour game with a pigeon as your guide",
  "A typing game where words are monsters marching toward your castle",
  "A gardening game where plants grow into puzzles you have to solve",
  "A space station repair game with a robot and a timer",
  "A ninja who can only move when the music plays",
  "A dragon who hoards cozy blankets instead of gold",
  "A puzzle about guiding sheep into their pen with a sheepdog",
  "A volcano island where you build before the next eruption",
  "A minimalist tower stacking game where the wind gets stronger",
  "A post-apocalyptic bicycle courier on a cracked highway",
  "A pirate ship battle with cannons that shoot fruit",
  "A cozy café where you make latte art for forest animals",
  "A maze that rearranges itself every ten seconds",
  "A lantern-lit night market where you run a noodle stand",
  "A gravity golf game between tiny planets",
  "A firefly-catching game in a summer meadow at dusk",
  "A train track puzzle where you lay rails before the train arrives",
  "A robot learning to dance by copying your moves",
  "A cave diving game where your light slowly runs out",
  "A kite flying game through a festival of lanterns",
  "A castle siege where you defend with catapults and bad jokes",
  "A garden gnome sneaking through backyards at night",
  "A tiny racing game on a kitchen table with toy cars",
  "A dream world where doors lead to memories",
  "A vertical climber up a beanstalk above the clouds",
  "An underwater city builder with bubble domes",
  "A shop keeping game in a fantasy town that sells only potions",
  "A spooky graveyard where you help lost ghosts find home",
  "A snowball fight arena with forts that you build yourself",
  "A side-scrolling skateboarding game through a neon city",
  "A starship captain choosing which planet to visit next",
  "A word puzzle where letters fall like rain",
  "A toy soldier battle on a bedroom floor",
  "A drift racer on frozen mountain roads at night",
  "A cozy puzzle about packing a suitcase for a trip",
  "A jungle temple escape with rolling boulders and traps",
  "A comet herding game where you guide ice rocks into orbit",
  "A mail sorting game in a busy post office before closing time",
  "A balloon pop game with a hedgehog that rolls through the sky",
  "A tiny wizard school where you mix colors into spells",
  "A canal city where you steer a gondola through narrow streets",
  "A greenhouse where every plant has a strange personality",
  "A clockwork tower where you fix gears to reach the top",
  "A soccer game played by robots on a tiny pitch",
  "A meteor shower dodge game with a small dinosaur",
  "A bakery rush where orders pile up on a conveyor belt",
  "A pathfinding puzzle with mirrors and laser beams",
  "A mountain rescue game with a dog and a sled",
  "A sci-fi hacking game where you route signals through circuits",
  "A tide pool explorer collecting shells before the waves return",
  "A cozy library where you match lost books to their readers",
  "A juggling game where the balls are on fire",
  "A ghost ship sailing through a sea of clouds",
  "A garden defense game where vegetables guard against snails",
  "A starlit camping trip where you build the perfect campfire",
] as const;

/** A random idea from the list, never the one just shown. */
export function pickPromptIdea(previous: string | null, random: () => number = Math.random): string {
  const others = PROMPT_IDEAS.filter((idea) => idea !== previous);
  return others[Math.floor(random() * others.length)] ?? PROMPT_IDEAS[0];
}
